Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2023-08, with the labels that each got.

#2283 MGMT-15377: ARM64 OCP 4.10 cluster - CMN should be blocked in UI
  libs/ui-lib/lib/common/components/clusterWizard/networkingSteps/ManagedNetworkingControlGroup.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
Labels: size/L, jira/valid-reference

#2284 MGMT-15414: When "No partner integration" is selected allow the BE to determine the platform type
  libs/ui-lib-tests/cypress/integration/create-multinode/0-create-cluster.cy.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
  libs/ui-lib-tests/cypress/views/clusterDetails.ts
  libs/ui-lib-tests/cypress/views/common.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/ExternalPlatformDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegrationNote.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailStatusMessages.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterPlatformIntegrationHint.tsx
  libs/ui-lib/lib/ocm/services/ClusterDetailsService.ts
Labels: lgtm, size/L, OCM, jira/valid-reference

#2219 MGMT-14644: Fix missing I18N in action names
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvAgentTable.tsx
  libs/ui-lib/lib/common/components/hosts/EditHostForm.tsx
  libs/ui-lib/lib/common/components/hosts/EditHostModal.tsx
  libs/ui-lib/lib/common/components/hosts/HostToolbarActions.tsx
  libs/ui-lib/lib/common/components/hosts/tableUtils.tsx
  libs/ui-lib/lib/ocm/components/hosts/use-hosts-table.tsx
Labels: lgtm, size/M, jira/valid-reference

#2258 MGMT-15410: Add unit tests for OCM wizard transitions
  libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.test.ts
  libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts
Labels: lgtm, size/L, jira/valid-reference

#2268 OCPBUGS-16077: fix base domain name validation
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.test.ts
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
Labels: size/M, jira/severity-critical, OCM, jira/valid-reference

#2287 MGMT-14911: Add host configuration sends last yaml when text already deleted
  libs/ui-lib/lib/common/components/ui/formik/CodeField.tsx
Labels: size/XS, OCM, jira/valid-reference

#2295 MGMT-14774: Add hosts cluster events - no events related to previous added hosts
  libs/ui-lib/lib/common/components/ui/ClusterEventsToolbar.tsx
Labels: size/XS, OCM, jira/valid-reference

#2302 OCPBUGS-16077: problems regexp base domain - followup - 2.24
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.test.ts
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
Labels: lgtm, size/XS, jira/invalid-bug, jira/severity-critical, jira/valid-reference

#2299 MGMT-11177: Update UX of Dropdowns to match Patternfly style
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmBaseDomainField.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
  libs/ui-lib/lib/ocm/components/ui/OcmFormFields.tsx
Labels: lgtm, size/L, OCM, jira/valid-reference

#2292 MGMT-14678: Day2 - host not showing up in the UI session that generated it, but is shown in another session
  libs/ui-lib-tests/cypress/integration/day-2/1-first-access.cy.ts
  libs/ui-lib-tests/cypress/support/interceptors.ts
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
Labels: size/S, OCM, jira/valid-reference

#2297 MGMT-15075: Day2 - Do not request custom manifests
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardContext.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardContextProvider.tsx
  libs/ui-lib/lib/ocm/components/hosts/ClusterHostsTable.tsx
  libs/ui-lib/lib/ocm/components/hosts/use-hosts-table.tsx
Labels: lgtm, size/M, OCM, jira/valid-reference

#2291 MGMT-14965: When UMN selected - no need to show "Machine networks CIDR" as its empty
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewNetworkingTable.tsx
Labels: size/S, OCM, jira/valid-reference

#2293 MGMT-15358, MGMT-10605: Links to documentation and 'What's new'
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx
Labels: size/S, OCM, jira/valid-reference

#2286 MGMT-15054: FCP devices (multipath) do not show correct size
  libs/ui-lib-tests/cypress/fixtures/storage/host-inventory.ts
  libs/ui-lib-tests/cypress/fixtures/storage/storage-hosts.ts
  libs/ui-lib-tests/cypress/integration/create-multinode/1-host-discovery.cy.ts
  libs/ui-lib-tests/cypress/integration/storage/storage-step-disk-holders.cy.ts
  libs/ui-lib-tests/cypress/integration/storage/storage-step.cy.ts
  libs/ui-lib-tests/cypress/support/variables/test-constants.ts
  libs/ui-lib-tests/cypress/views/hostsTableSection.ts
  libs/ui-lib/lib/common/components/hosts/hardwareInfo.ts
Labels: lgtm, size/M, OCM

#2296 MGMT-14782: The message about formatting available disks should be more specific
  libs/ui-lib/lib/common/components/hosts/FormatDiskCheckbox.tsx
  libs/ui-lib/lib/ocm/components/hosts/OdfDisksManualFormattingHint.tsx
Labels: size/XS, OCM, jira/valid-reference

#2288 MGMT-15528: Use labels if status lacks OCP version
  libs/ui-lib/lib/cim/components/common/constants.ts
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
Labels: lgtm, size/S, jira/valid-reference

#2303 MGMT-14053: Add "?" icon and a explanation text popover to the " WWN" column
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/common/components/storage/DisksTable.tsx
Labels: lgtm, size/S, OCM, jira/valid-reference

#2276 MGMT-15361: Disable external partner integration option when integration is not supported
  libs/ui-lib-tests/cypress/integration/features/read-only-multi-node.cy.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetails/Fields/ExternalPartnerIntegrationsField.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
  libs/ui-lib/lib/ocm/hooks/useOracleDropdownItemState.ts
Labels: lgtm, size/L, OCM, jira/valid-reference

#2309 MGMT-14692: Hover over OVN when network type is disabled displays text related to SDN
  libs/locales/lib/en/translation.json
  libs/locales/lib/ja/translation.json
  libs/locales/lib/ko/translation.json
  libs/locales/lib/zh/translation.json
  libs/ui-lib/lib/common/components/clusterWizard/networkingSteps/NetworkTypeControlGroup.tsx
Labels: size/S, OCM, jira/valid-reference

#2308 OCPBUGS-16077: Problems base domain validation - remove validation from UI - 2.24
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.test.ts
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
Labels: lgtm, size/M, OCM

#2310 MGMT-15530: external platform integration dropdown - disable Nutanix and Vsphere when sno is selected
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetails/ClusterDetailsForm.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetails/Fields/SnoField.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
Labels: lgtm, size/M, OCM, jira/valid-reference

#2311 MGMT-15616: Hide OCI platform integration "learn more" link until we have correct link
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegrationNote.tsx
Labels: size/S, OCM, jira/valid-reference

#2312 MGMT-11874: Simplifies the app routes
  apps/assisted-ui/src/components/App/App.tsx
  libs/ui-lib/lib/ocm/components/Router.tsx
  libs/ui-lib/lib/ocm/components/Routes.tsx
  libs/ui-lib/lib/ocm/components/index.ts
Labels: lgtm, size/M, jira/valid-reference

#2315 MGMT-15666: Clear alerts when user click next button in cluster details form - 2.24
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
Labels: lgtm, size/XS, jira/valid-reference

#2314 MGMT-15666: Clear alerts when user clicks next button in cluster details form
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
Labels: size/XS, jira/valid-reference
