Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2023-10, with the labels that each got.

#2393 MGMT-15599: Add message when platform-requirements-satisfied validation fails
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/common/components/clusterWizard/ReviewValidations.tsx
  libs/ui-lib/lib/common/config/constants.ts
Labels: size/XS, OCM, jira/valid-reference

#2395 MGMT-15062: Remove references to ASSISTED_INSTALLER_MULTIARCH_SUPPORTED feature
  libs/ui-lib/lib/common/features/featureGate.tsx
  libs/ui-lib/lib/common/types/cpuArchitecture.ts
  libs/ui-lib/lib/ocm/components/AddHosts/AddHosts.tsx
  libs/ui-lib/lib/ocm/components/AddHosts/InventoryAddHost.tsx
  libs/ui-lib/lib/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
Labels: size/M, OCM, jira/valid-reference

#2396 MGMT-13220: Add disabled field tooltip on encryption type components
  libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionMode.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/TangServers.tsx
Labels: size/M, OCM, jira/valid-reference

#2397 MGMT-15597: Custom manifests - stop using fakeIds
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifests.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsArray.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/utils.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/data/dataTypes.ts
Labels: lgtm, size/L, OCM, jira/valid-reference

#2399 MGMT-15805 Set OVNKubernetes network type as default for 4.12+ clusters
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/helpers/versions.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx
  libs/ui-lib/lib/common/components/ui/formik/SelectField.tsx
  libs/ui-lib/lib/common/components/ui/formik/types.ts
Labels: lgtm, size/M

#2400 MGMT-15633 Improve NMState config msg
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
Labels: size/XS

#2402 [2.8] MGMT-15805 Set OVNKubernetes network type as default for 4.12+ clusters
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/helpers/versions.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx
  libs/ui-lib/lib/common/components/ui/formik/SelectField.tsx
  libs/ui-lib/lib/common/components/ui/formik/types.ts
Labels: size/M

#2401 [2.8] MGMT-15633 Improve NMState config msg
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
Labels: lgtm, size/XS

#2360 MGMT-14936: Remove user-managed-networking cluster attribute
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/networkConfigurationValidation.ts
  libs/ui-lib/lib/ocm/services/ClusterDetailsService.ts
Labels: size/S, jira/valid-reference

#2404 Nutanix day2: ensure that only nutanix agents are shown
  libs/ui-lib/lib/cim/components/ClusterDeployment/ScaleUpForm.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/utils.ts
  libs/ui-lib/lib/cim/components/modals/ScaleUpModal.tsx
  libs/ui-lib/lib/cim/types/k8s/agent-cluster-install.ts
Labels: lgtm, size/M

#2383 MGMT-15685: Allow the app to fetch capabilities
  .vscode/extensions.json
  .vscode/settings.json
  libs/ui-lib/lib/@types/assets.d.ts
  libs/ui-lib/lib/@types/global.d.ts
  libs/ui-lib/lib/_test-helpers/mock-container.ts
  libs/ui-lib/lib/_test-helpers/mock-server.ts
  libs/ui-lib/lib/_test-helpers/vitest-setup.ts
  libs/ui-lib/lib/cim/components/ClusterDeployment/_wizardTransition.test.ts
  libs/ui-lib/lib/cim/index.ts
  libs/ui-lib/lib/common/api/utils.ts
  libs/ui-lib/lib/common/components/ui/formik/_validationSchemas.test.ts
  libs/ui-lib/lib/common/index.ts
  libs/ui-lib/lib/common/types/index.ts
  libs/ui-lib/lib/common/types/resource-ui-state.ts
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTab.tsx
  libs/ui-lib/lib/ocm/components/Routes.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/_wizardTransition.test.ts
  libs/ui-lib/lib/ocm/config/external-features.ts
  libs/ui-lib/lib/ocm/config/index.ts
  libs/ui-lib/lib/ocm/config/routeBasePath.ts
  libs/ui-lib/lib/ocm/hooks/_use-feature-detection.test.tsx
  libs/ui-lib/lib/ocm/hooks/use-feature-detection.ts
  libs/ui-lib/lib/ocm/services/ClustersService.ts
  libs/ui-lib/lib/ocm/services/InfraEnvIdsCacheService.ts
  libs/ui-lib/lib/ocm/store/hooks.ts
  libs/ui-lib/lib/ocm/store/index.ts
  libs/ui-lib/lib/ocm/store/slices/clusters/slice.ts
  libs/ui-lib/lib/ocm/store/slices/current-cluster/slice.ts
  libs/ui-lib/lib/ocm/store/slices/current-user/slice.ts
  libs/ui-lib/lib/ocm/store/slices/feature-flags/selectors.ts
  libs/ui-lib/lib/ocm/store/slices/feature-flags/slice.ts
  libs/ui-lib/lib/ocm/store/slices/infra-envs/thunks.ts
  libs/ui-lib/lib/ocm/store/store-day1.ts
  libs/ui-lib/lib/ocm/store/store-day2.ts
  libs/ui-lib/lib/ocm/store/types/state-slice.ts
  libs/ui-lib/package.json
  libs/ui-lib/tsconfig.eslint.json
  libs/ui-lib/tsconfig.json
  libs/ui-lib/vitest.config.ts
  package.json
  vitest.workspace.json
  yarn.lock
Labels: lgtm, size/XXL, jira/valid-reference

#2410 MGMT-15952: Declaring PF4 as a direct dependency
  libs/ui-lib/package.json
  yarn.lock
Labels: lgtm, size/S, OCM, jira/valid-reference

#2411 MGMT-15049: Add warning icon and i18n to delete host modal
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/ocm/components/hosts/DeleteHostModal.tsx
Labels: lgtm, size/M, jira/valid-reference

#2413 MGMT-15952: Declaring PF4 as a direct dependency - followup
  libs/ui-lib/package.json
  yarn.lock
Labels: lgtm, size/S, OCM, jira/valid-reference

#2414 NO-ISSUE: Exposes authorization-service.d.ts
  libs/types/package.json
Labels: lgtm, size/XS, jira/valid-reference

#2416 CIM: Handle case when admin credentials are not available
  locales/en/translation.json
  src/cim/components/ClusterDeployment/ClusterDeploymentCredentials.tsx
  src/common/components/clusterDetail/ClusterCredentials.tsx
Labels: lgtm, size/M

#2417 MGMT-15974: [PSI / On-prem] - Day2 - After adding new host, day1 hosts move to Finalizing status
  libs/ui-lib/lib/common/components/hosts/utils.ts
Labels: lgtm, size/XS, OCM, jira/valid-reference

#2418 MGMT-15251: Link to infra env page instead of networking in case of n…
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/ClusterDeployment/wizardTransition.ts
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
  libs/ui-lib/lib/common/components/clusterWizard/ReviewValidations.tsx
  libs/ui-lib/lib/common/components/clusterWizard/types.ts
  libs/ui-lib/lib/common/components/clusterWizard/validationsInfoUtils.ts
Labels: lgtm, size/M, jira/valid-reference

#2419 MGMT-15140: Do not report delayed CIM config as an error
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/modals/CimConfiguration/CimConfigProgressAlert.tsx
  libs/ui-lib/lib/cim/components/modals/CimConfiguration/constants.ts
Labels: size/S, jira/valid-reference

#2409 MGMT-15919: If day1 cluster is ARM cpu arch, then only ARM nodes can be added in Day2
  libs/ui-lib/lib/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx
Labels: lgtm, size/S, OCM, jira/valid-reference

#2420 [2.7] Update push-to-master.yaml
  .github/workflows/on-push.yaml
Labels: lgtm, size/XS

#2421 [2.8] Update push-to-master.yaml
  .github/workflows/push-to-master.yaml
Labels: size/XS

#2422 MGMT-16030 Filter out non-nutanix agents
  libs/ui-lib/lib/cim/components/ClusterDeployment/ScaleUpForm.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/index.ts
  libs/ui-lib/lib/cim/components/InfraEnv/utils.ts
  libs/ui-lib/lib/cim/types/k8s/agent-cluster-install.ts
Labels: lgtm, size/L

#2426 MGMT-16041: Splits the preview badges into one component per module
  libs/ui-lib/lib/common/components/featureSupportLevels/FeatureSupportLevelBadge.tsx
  libs/ui-lib/lib/common/components/newFeatureSupportLevels/NewFeatureSupportLevelBadge.tsx
  libs/ui-lib/lib/common/components/ui/DeveloperPreview.tsx
  libs/ui-lib/lib/common/components/ui/PreviewBadge.tsx
  libs/ui-lib/lib/common/components/ui/TechnologyPreview.tsx
  libs/ui-lib/lib/common/components/ui/index.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
Labels: size/L, jira/valid-reference

#2427 MGMT-16069: OCI is enabled if SNO + OCP version < 4.14 - should be blocked
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
Labels: lgtm, size/S, OCM, jira/valid-reference
