Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2023-03, with the labels that each got.

#1938 MGMT-13700: Add learn more link for LVMS operator
  src/common/config/constants.ts
  src/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx
Labels: OCM, jira/valid-reference

#1962 MGMT-13855: Base domain field validation causing the UI to get stuck
  src/common/components/ui/formik/validationSchemas.ts
Labels: OCM, jira/valid-reference

#1961 MGMT-13855: Base domain field validation causing the UI to get stuck (2.16)
  src/common/components/ui/formik/validationSchemas.ts
Labels: OCM, jira/valid-reference

#1963 MGMT-13856: LVMS should be enabled for SNO+ARM clusters
  src/ocm/components/featureSupportLevels/featureStateUtils.ts
Labels: OCM, jira/valid-reference

#1964 MGMT-13856: LVMS should be enabled for SNO+ARM clusters - 2.16
  src/ocm/components/featureSupportLevels/featureStateUtils.ts
Labels: OCM, jira/valid-reference

#1960 MGMT-13154 - LVMO link hyper element of checkbox is extended until start of Developer Preview button
  src/common/components/ui/PreviewBadge.tsx
Labels: OCM

#1957 MGMT-12603 - Network Type selector when there is only 1 valid option
  src/common/components/clusterWizard/networkingSteps/NetworkTypeControlGroup.tsx
Labels: OCM

#1950 MGMT-13751: Improve validations in additional certificates field
  locales/en/translation.json
  src/common/components/clusterConfiguration/CertificateFields.css
  src/common/components/clusterConfiguration/CertificateFields.tsx
  src/common/components/ui/formik/CertificatesUploadField.tsx
Labels: OCM, jira/valid-reference

#1972 MGMT-13702 - Copy nmstate configuration must be enabled by default
  src/ocm/components/clusterConfiguration/staticIp/components/StaticIpHostsArray.tsx
Labels: OCM

#1951 MGMT-13701 - API and Ingress VIPs fields should not allow broadcast IPs
  src/common/components/ui/formik/utils.ts
  src/common/components/ui/formik/validationSchemas.ts
Labels: OCM

#1952 MGMT-13728 - Platform helper text should be reformatted
  src/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegration.tsx
Labels: OCM

#1971 Discourage / prevent the average user from choosing older z versions
  src/common/components/ui/OpenShiftVersionDropdown.tsx
Labels: OCM

#1955 MGMT-13790 - Day2 "set the IP or domain used to reach the cluster" modal closing issues
  src/ocm/components/hosts/UpdateDay2ApiVipModal.tsx
Labels: OCM

#1954 MGMT-13649 - SNO cluster - R&C page - no API and Ingress IPs info
  src/ocm/components/clusterConfiguration/review/ReviewNetworkingTable.tsx
Labels: OCM

#1956 MGMT-12331 - Remove Format column in the Host discovery page
  src/common/components/storage/DisksTable.tsx
Labels: OCM

#1969 MGMT-11395 - Improve cluster and hosts deletion experience
  src/ocm/components/clusters/Clusters.tsx
  src/ocm/components/clusters/ClustersTable.tsx
  src/ocm/components/clusters/DeleteClusterModal.tsx
Labels: OCM

#1953 MGMT-13783: Link to set iso login password script is not working and text is unclear
  locales/en/translation.json
  src/common/components/clusterConfiguration/DiscoveryTroubleshootingModal.tsx
Labels: OCM, jira/valid-reference

#1973 Fix missing key in Openshift version dropdown
  src/common/components/ui/OpenShiftVersionDropdown.tsx
Labels: OCM

#1980 MGMT-13919: Fix spacing between help texts for Hosts
  src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx
Labels: jira/valid-reference

#1967 MGMT-13499: Add separate handling for progressing conditions
  src/cim/components/Hypershift/DetailsPage/ConditionsTable.tsx
Labels: jira/valid-reference

#1968 MGMT-12928: Add separate handling for progressing conditions
  src/cim/components/Hypershift/DetailsPage/ConditionsTable.tsx
Labels: jira/valid-reference

#1975 MGMT-13573: Propagate agent's spec sync error to status
  locales/en/translation.json
  src/cim/components/Agent/AgentStatus.tsx
  src/cim/components/common/SpecSyncErrAlert.tsx
  src/cim/components/helpers/agentStatus.tsx
  src/cim/components/helpers/status.ts
Labels: jira/valid-reference

#1982 MGMT-13262: Enable setting host prefix for hypershift clusters
  src/cim/components/ClusterDeployment/networkConfigurationValidation.ts
  src/cim/components/ClusterDeployment/use-networking-formik.ts
  src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkForm.tsx
  src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkStep.tsx
  src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/types.ts
  src/common/components/ui/formik/validationSchemas.ts
Labels: jira/valid-reference

#1978 MGMT-13228: Propagate errors from infra env to add host modal
  locales/en/translation.json
  src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx
  src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx
  src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx
  src/cim/components/ClusterDeployment/types.ts
  src/cim/components/InfraEnv/AddHostDropdown.css
  src/cim/components/InfraEnv/AddHostDropdown.tsx
  src/cim/components/InfraEnv/EnvironmentErrors.tsx
  src/cim/components/InfraEnv/index.ts
  src/cim/components/InfraEnv/types.ts
  src/cim/components/modals/AddBmcHostModal.tsx
  src/cim/components/modals/AddBmcHostYamlForm.tsx
  src/cim/components/modals/AddBmcHostYamlModal.tsx
  src/cim/components/modals/AddHostModal.tsx
  src/cim/components/modals/types.ts
Labels: jira/valid-reference

#1985 MGMT-9907: CIM: Enable setting installation disk
  src/cim/components/ClusterDeployment/ClusterDeploymentHostsNetworkTable.tsx
  src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingForm.tsx
  src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx
  src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx
  src/cim/components/ClusterDeployment/types.ts
Labels: jira/valid-reference

#1987 MGMT-9939: CIM: Provide iPXE artifacts in discovery image dialog UI
  locales/en/translation.json
  src/cim/components/InfraEnv/AddHostDropdown.tsx
  src/cim/components/modals/AddHostModal.tsx
  src/cim/components/modals/types.ts
  src/cim/types/k8s/infra-env-k8s-resource.ts
  src/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx
Labels: jira/valid-reference

#1988 MGMT-9941: CIM: Allow setting user managed networking for non-SNO clusters
  src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingForm.tsx
  src/cim/components/ClusterDeployment/NetworkConfiguration.tsx
  src/cim/components/helpers/toAssisted.ts
  src/cim/types/k8s/agent-cluster-install.ts
  src/common/components/clusterWizard/networkingSteps/ManagedNetworkingControlGroup.tsx
Labels: jira/valid-reference

#1970 MGMT-13599: Changes in day2 to add new IBM cpu architectures
  src/common/components/clusterConfiguration/utils.ts
  src/common/selectors/clusterSelectors.ts
  src/common/types/cpuArchitecture.ts
  src/ocm/api/axiosClient.ts
  src/ocm/components/AddHosts/AddHosts.tsx
  src/ocm/components/AddHosts/InventoryAddHost.tsx
  src/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
  src/ocm/components/AddHosts/types.ts
  src/ocm/components/HostsClusterDetailTab/HostsClusterDetailTab.tsx
  src/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
  src/ocm/components/HostsClusterDetailTab/types.ts
  src/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx
  src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  src/ocm/components/clusterConfiguration/OcmOpenShiftVersion.tsx
  src/ocm/components/clusterWizard/ClusterDetailsForm.tsx
  src/ocm/hooks/useArchitecturesSupportLevels.ts
  src/ocm/hooks/useCpuArchitectures.ts
  src/ocm/services/ClusterDetailsService.ts
  src/ocm/services/Day2ClusterService.ts
  src/ocm/services/apis/NewFeatureSupportLevelsAPI.ts
Labels: OCM, jira/valid-reference

#1995 MGMT-14122: Hypershift: Remove machine CIDR dropdown
  src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkForm.tsx
  src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/NetworkStep.tsx
  src/cim/components/Hypershift/HostedClusterWizard/NetworkStep/types.ts
Labels: jira/valid-reference

#1997 MGMT-14138: CIM Hypershift: Fix details page link from Agent to Cluster
  src/cim/components/Agent/tableUtils.tsx
  src/cim/components/ClusterDeployment/types.ts
  src/cim/components/InfraEnv/InfraEnvAgentTable.tsx
Labels: jira/valid-reference

#1998 MGMT-14130: Disable changing labels when editing nodepool
  src/cim/components/Hypershift/forms/NodePoolAgentsForm.tsx
  src/cim/components/Hypershift/modals/NodePoolForm.tsx
Labels: jira/valid-reference
