Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2023-04, with the labels that each got.

#1989 MGMT-9613: CIM: Integrate InfraEnv form with ACM's credentials
  src/cim/components/InfraEnv/InfraEnvFormPage.tsx
Labels: jira/valid-reference

#2008 MGMT-14214: Disable and uncheck SNO checkbox when choose IBM Power or IBM Z archs - 2.18
  src/ocm/components/clusterConfiguration/OcmSingleNodeCheckbox.tsx
Labels: OCM, jira/valid-reference

#2009 MGMT-14214: Disable and uncheck SNO checkbox when choose IBM Power or IBM Z archs
  src/ocm/components/clusterConfiguration/OcmSingleNodeCheckbox.tsx
Labels: OCM, jira/valid-reference

#2011 MGMT-14225: New support level unavailable added - 2.18
  src/common/api/swagger.yaml
  src/common/api/types.ts
  src/common/types/cpuArchitecture.ts
  src/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
  src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
  src/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx
  src/ocm/components/featureSupportLevels/featureStateUtils.ts
  src/ocm/components/newFeatureSupportLevels/NewFeatureSupportLevelProvider.tsx
  src/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts
  src/ocm/services/Day2ClusterService.ts
Labels: OCM, jira/valid-reference

#2010 MGMT-14225: New support level unavailable added
  src/common/api/swagger.yaml
  src/common/api/types.ts
  src/common/types/cpuArchitecture.ts
  src/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
  src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  src/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
  src/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx
  src/ocm/components/featureSupportLevels/featureStateUtils.ts
  src/ocm/components/newFeatureSupportLevels/NewFeatureSupportLevelProvider.tsx
  src/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts
  src/ocm/services/Day2ClusterService.ts
Labels: OCM, jira/valid-reference

#2017 MGMT-14216: Don't fail CIM configuration on unsuccessful provisioning configuration
  locales/en/translation.json
  src/cim/components/modals/CimConfiguration/persist.ts
Labels: jira/valid-reference

#2020 [2.7-cim] MGMT-14216: Don't fail CIM configuration on unsuccessful provisioning configuration
  locales/en/translation.json
  src/cim/components/modals/CimConfiguration/persist.ts
Labels: jira/valid-reference

#2019 [2.7-cim] MGMT-13319: Fix translation for NoAgentsAlert component
  locales/en/translation.json
  src/cim/components/Agent/NoAgentsAlert.tsx
Labels: jira/valid-reference

#2022 MGMT-14270: We need to show 'Add hosts' tab to cluster with 'installed' status - 2.18
  src/ocm/components/HostsClusterDetailTab/utils.ts
Labels: jira/valid-reference

#2021 MGMT-14270: We need to show 'Add hosts' tab to cluster with 'installed' status
  src/ocm/components/HostsClusterDetailTab/utils.ts
Labels: OCM, jira/valid-reference

#1994 MGMT-13265: CIM: Move InfraEnv proxy configuration to details page
  locales/en/translation.json
  src/cim/components/InfraEnv/EnvironmentDetails.tsx
  src/cim/components/modals/AddHostModal.tsx
  src/cim/components/modals/EditProxyModal.tsx
  src/cim/components/modals/index.ts
  src/cim/components/modals/types.ts
  src/common/components/clusterConfiguration/DownloadIpxeScript.tsx
Labels: jira/valid-reference

#2006 MGMT-14209: CIM: Enable setting installation disk in scaleup modal
  src/cim/components/ClusterDeployment/ScaleUpForm.tsx
  src/cim/components/modals/ScaleUpModal.tsx
Labels: jira/valid-reference

#2024 MGMT-14262: Put correct CPU architecture in dropdown when OCP version changed - 2.18
  src/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx
Labels: OCM

#2026 MGMT-14267: CNV will be disabled for P/Z clusters - 2.18
  src/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts
Labels: OCM, jira/valid-reference

#2025 MGMT-14267: CNV will be disabled for P/Z clusters
  src/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts
Labels: OCM, jira/valid-reference

#2023 MGMT-14262: Put correct CPU architecture in dropdown when OCP version changed
  src/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx
Labels: OCM

#2028 MGMT-14170: In Add hosts modal disable minimal ISO and ipxe for s390 architecture - 2.18
  src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx
  src/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx
  src/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx
Labels: OCM, jira/valid-reference

#2014 MGMT-14160: CIM: Make pull secret required and show field error messages after su…
  src/cim/components/ClusterDeployment/ACMClusterDeploymentDetailsStep.tsx
  src/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
  src/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx
  src/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  src/cim/components/ClusterDeployment/types.ts
  src/common/hooks/useFieldErrorMsg.tsx
Labels: jira/valid-reference

#2016 MGMT-14081: CIM: Fix VIPs description typo
  locales/en/translation.json
  src/common/components/clusterWizard/networkingSteps/VirtualIPControlGroup.tsx
Labels: jira/valid-reference

#2012 MGMT-14207: CIM: Fix ts errors
  src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx
  src/cim/components/ClusterDeployment/types.ts
  src/cim/components/ClusterDeployment/wizardTransition.ts
  src/cim/components/Hypershift/forms/NodePoolAgentsForm.tsx
  src/cim/components/Hypershift/modals/ManageHostsModal.tsx
Labels: jira/valid-reference

#2030 MGMT-14290: Filling CpuArchitectureDropdown from release image architectures
  src/common/types/cpuArchitecture.ts
  src/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
  src/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
  src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  src/ocm/services/Day2ClusterService.ts
Labels: OCM

#2031 MGMT-14290: Filling CpuArchitectureDropdown from release image architectures - 2.18
  src/common/types/cpuArchitecture.ts
  src/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
  src/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
  src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  src/ocm/services/Day2ClusterService.ts
Labels: OCM, jira/valid-reference

#2036 MGMT-14320: Power Z clusters can be only homogeneous clusters - 2.18
  src/common/types/cpuArchitecture.ts
  src/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
  src/ocm/components/clusterDetail/ClusterProperties.tsx
Labels: OCM, jira/valid-reference

#2037 MGMT-14320: s390 clusters should be homogeneous
  src/common/types/cpuArchitecture.ts
Labels: OCM, jira/valid-reference

#2039 MGMT-14320: Problems in 'Add hosts' tab for Power/Z clusters
  src/ocm/services/Day2ClusterService.ts
Labels: OCM, jira/valid-reference

#2043 MGMT-14170: Allow ipxe script download for s390 clusters - 2.18
  src/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx
Labels: OCM, jira/valid-reference

#2042 MGMT-14170: Allow ipxe script download for s390 clusters
  src/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx
Labels: OCM, jira/valid-reference

#2013 MGMT-14168: CIM: Allow setting doc version for user-managed doc link
  src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingForm.tsx
  src/cim/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx
  src/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx
  src/cim/components/ClusterDeployment/NetworkConfiguration.tsx
  src/cim/components/ClusterDeployment/types.ts
  src/common/components/clusterWizard/networkingSteps/UserManagedNetworkingTextContent.tsx
  src/common/config/constants.ts
  src/ocm/components/clusterConfiguration/networkConfiguration/UserManagedNetworkingTextContent.tsx
Labels: jira/valid-reference

#2015 MGMT-14148: CIM: Remove dot in iPXE description
  locales/en/translation.json
  src/cim/components/InfraEnv/AddHostDropdown.tsx
Labels: jira/valid-reference

#1986 MGMT-13837: "Hosts not showing up?" modal redesign
  locales/en/translation.json
  src/common/components/clusterConfiguration/DiscoveryTroubleshootingModal.tsx
  src/common/components/ui/PrismCode.tsx
  src/common/components/ui/index.ts
  src/ocm/components/hosts/HostsDiscoveryTroubleshootingInfoLinkWithModal.tsx
Labels: OCM, jira/valid-reference

#2005 MGMT-14052: Remove disks section in host discovery step
  src/common/components/hosts/HostRowDetail.tsx
Labels: OCM, jira/valid-reference

#1976 MGMT-13334: Failed to load feature support levels preview
  src/common/components/ErrorHandling/WithErrorBoundary.tsx
  src/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx
Labels: OCM, jira/valid-reference

#2032 MGMT-14197 - "No proxy domains" field is missing validations
  src/common/components/ui/formik/validationSchemas.ts
Labels: OCM

#1993 MGMT-13731: Override the hosts' "installed" status
  src/common/components/hosts/status.tsx
  src/common/components/hosts/tableUtils.tsx
  src/common/components/hosts/utils.ts
  src/ocm/components/hosts/ClusterHostsTable.tsx
Labels: OCM, jira/valid-reference

#2033 MGMT-14200 - Change cluster network CIDR copy
  src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx
Labels: OCM

#2034 MGMT-14201 - Service network CIDR description text split
  src/ocm/components/clusterConfiguration/networkConfiguration/AdvancedNetworkFields.tsx
Labels: OCM

#2047 MGMT-14051 - We should show a tooltip explaining why a bootable disk cannot be formatted when hovering the checkbox
  src/common/components/hosts/FormatDiskCheckbox.tsx
Labels: OCM

#1966 MGMT-9166 - Help text disappears once there is an error
  src/common/components/clusterConfiguration/SecurityFields.tsx
  src/common/components/ui/formik/CheckboxField.tsx
  src/common/components/ui/formik/CodeField.tsx
  src/common/components/ui/formik/InputField.tsx
  src/common/components/ui/formik/LabelField.tsx
  src/common/components/ui/formik/MultiSelectField.tsx
  src/common/components/ui/formik/NumberInputField.tsx
  src/common/components/ui/formik/PullSecretField.tsx
  src/common/components/ui/formik/SelectField.tsx
  src/common/components/ui/formik/SwitchField.tsx
  src/common/components/ui/formik/TextAreaField.tsx
  src/common/components/ui/formik/UploadField.tsx
Labels: OCM

#2050 MGMT-14398: In 'Add hosts' modal when we select ipXe, additional options for InfraEnv should be saved
  src/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx
  src/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx
  src/ocm/services/DiscoveryImageFormService.ts
Labels: OCM, jira/valid-reference

#1992 MGMT-13701 - API and Ingress VIPs fields should not allow broadcast IPs
  src/common/components/ui/formik/validationSchemas.ts
Labels: OCM

#2041 MGMT-14307 - Day2 - In add hosts - setting "control plane" role to host but UI marks it as control plane + worker
  src/common/components/hosts/RoleCell.tsx
  src/common/components/hosts/RoleDropdown.tsx
  src/common/components/hosts/tableUtils.tsx
  src/common/components/hosts/utils.ts
  src/common/components/ui/SimpleDropdown.tsx
  src/ocm/components/hosts/ClusterHostsTable.tsx
  src/ocm/components/hosts/HostsDiscoveryTable.tsx
Labels: OCM

#2049 MGMT-14345: CIM: Handle case when admin credentials are not available
  locales/en/translation.json
  src/cim/components/ClusterDeployment/ClusterDeploymentCredentials.tsx
  src/common/components/clusterDetail/ClusterCredentials.tsx
Labels: jira/valid-reference

#2046 MGMT-14048 - Change "Run workloads on control plane nodes" tooltip when disabled
  src/ocm/components/clusterConfiguration/HostInventory.tsx
Labels: OCM

#2056 MGMT-14343: CIM: Use installed icon for day2 hosts
  src/common/components/hosts/HostStatus.tsx
Labels: jira/valid-reference

#1835 MGMT-12919: Add an option to upload custom manifests using the UI
  src/common/api/swagger.yaml
  src/common/api/types.ts
  src/common/components/ui/formik/CodeField.tsx
  src/common/components/ui/formik/UploadField.tsx
  src/common/components/ui/formik/types.ts
  src/common/config/constants.ts
  src/ocm/components/clusterConfiguration/CustomManifestCheckbox.tsx
  src/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  src/ocm/components/clusterConfiguration/manifestsConfiguration/CustomManifestsPage.tsx
  src/ocm/components/clusterConfiguration/manifestsConfiguration/DeleteCustomManifestModal.tsx
  src/ocm/components/clusterConfiguration/manifestsConfiguration/components/CollapsedManifest.tsx
  src/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifest.tsx
  src/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifests.tsx
  src/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsArray.tsx
  src/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx
  src/ocm/components/clusterConfiguration/manifestsConfiguration/components/ExpandedManifest.tsx
  src/ocm/components/clusterConfiguration/manifestsConfiguration/components/FolderDropdown.tsx
  src/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx
  src/ocm/components/clusterConfiguration/manifestsConfiguration/components/propTypes.ts
  src/ocm/components/clusterConfiguration/manifestsConfiguration/components/utils.tsx
  src/ocm/components/clusterConfiguration/manifestsConfiguration/data/dataTypes.ts
  src/ocm/components/clusterConfiguration/review/ReviewCustomManifestsTable.tsx
  src/ocm/components/clusterConfiguration/review/ReviewSummary.tsx
  src/ocm/components/clusterConfiguration/staticIp/commonValidationSchemas.tsx
  src/ocm/components/clusterConfiguration/staticIp/components/StaticIpPage.tsx
  src/ocm/components/clusterWizard/ClusterDetails.tsx
  src/ocm/components/clusterWizard/ClusterDetailsForm.tsx
  src/ocm/components/clusterWizard/ClusterWizard.tsx
  src/ocm/components/clusterWizard/ClusterWizardContext.tsx
  src/ocm/components/clusterWizard/ClusterWizardContextProvider.tsx
  src/ocm/components/clusterWizard/CustomManifestStep.tsx
  src/ocm/components/clusterWizard/constants.ts
  src/ocm/components/clusterWizard/wizardTransition.ts
  src/ocm/hooks/useClusterCustomManifests.ts
  src/ocm/services/ClustersService.ts
  src/ocm/services/apis/ClustersAPI.ts
Labels: OCM, jira/valid-reference

#2051 MGMT-14131 - When AI service is down, AI cluster list is hang with loading sign
  src/ocm/components/clusterDetail/ClusterPollingErrorModal.tsx
  src/ocm/components/clusters/Clusters.tsx
  src/ocm/reducers/clusters/clustersSlice.ts
Labels: OCM

#2057 MGMT-14257: CIM: Update add hosts instructions
  locales/en/translation.json
  src/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx
Labels: jira/valid-reference

#2053 MGMT-13960: CIM: Fix typo in location field description
  locales/en/translation.json
  src/cim/components/ClusterDeployment/LocationsSelector.tsx
Labels: jira/valid-reference

#2052 MGMT-13542: CIM: Fallback to image url if version cannot be parsed
  src/cim/components/Hypershift/modals/NodePoolForm.tsx
Labels: jira/valid-reference

#2063 Use custom resolve conditions ('source' instead of 'development')
  apps/assisted-ui/vite.config.ts
  libs/ui-lib/package.json
Labels: size/XS

#2066 Fixes "command not found: toolbox"
  apps/assisted-ui/package.json
  libs/ui-lib/package.json
  package.json
  yarn.lock
Labels: lgtm, size/S

#2067 NO-ISSUE: Fixes the instructions for running the stand-alone UI app
  README.md
Labels: size/XS, jira/valid-reference

#2072 NO-ISSUE: Fixes the issue with the toolbox watch command
  apps/assisted-ui/package.json
  libs/ui-lib/package.json
  package.json
  yarn.lock
Labels: size/S, jira/valid-reference

#2073 NO-ISSUE: Do not sleep after publishing the second package
  .github/workflows/release.yaml
Labels: size/S, jira/valid-reference

#2064 NO-ISSUE: Do not sleep after publishing the second package
  .github/workflows/release.yaml
Labels: size/S, jira/valid-reference

#2070 MGMT-14447: Add id to kubeconfig download button
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewSummary.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/TableSummaryExpandable.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterSummaryExpandable.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/HostInventoryExpandable.tsx
Labels: size/S, OCM
