Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2023-06, with the labels that each got.

#2149 Quick edit II
  libs/locales/lib/en/translation.json
  libs/ui-lib-tests/cypress/support/variables/storage-step.ts
Labels: lgtm, approved, size/L

#2178 MGMT-14806: Fix error in view installed cluster - 2.21
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx
Labels: lgtm, approved, size/M, OCM, jira/valid-reference

#2179 MGMT-14806: Fix error in view installed cluster
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx
Labels: size/M, OCM, jira/valid-reference

#2181 MGMT-14807: Change base domain validation regexp to avoid catastrophic backtracking problems - 2.21
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
Labels: approved, size/XS, OCM, jira/valid-reference

#2180 MGMT-14807: Change base domain validation regexp to avoid catastrophic backtracking problems
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
Labels: size/XS, OCM, jira/valid-reference

#2185 MGMT-14658: Generate iso modal - not able to drag and drop ssh key [BACKPORT]
  apps/assisted-ui/package.json
  yarn.lock
Labels: lgtm, approved, size/XXL, OCM, jira/valid-reference

#2186 MGMT-14127: UI support for OCI platform
  apps/assisted-ui/src/main.tsx
  libs/eslint-config-assisted-ui/index.js
  libs/ui-lib-tests/cypress/fixtures/storage/storage-cluster.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
  libs/ui-lib-tests/cypress/views/clusterDetails.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetailsForm.ts
  libs/ui-lib-tests/cypress/views/pages/NewClusterPage.ts
  libs/ui-lib/lib/common/api/swagger.yaml
  libs/ui-lib/lib/common/api/types.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/utils.ts
  libs/ui-lib/lib/common/components/clusterWizard/networkingSteps/VirtualIPControlGroup.tsx
  libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx
  libs/ui-lib/lib/common/components/ui/StaticTextField.tsx
  libs/ui-lib/lib/common/components/ui/formik/CheckboxField.tsx
  libs/ui-lib/lib/common/components/ui/formik/InputField.tsx
  libs/ui-lib/lib/common/components/ui/formik/RichInputField.tsx
  libs/ui-lib/lib/common/components/ui/formik/SelectField.tsx
  libs/ui-lib/lib/common/components/ui/formik/TextAreaField.tsx
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/common/features/featureGate.tsx
  libs/ui-lib/lib/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/CustomManifestCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/HostsNetworkConfigurationControlGroup.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmSingleNodeCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/VirtualIPControlGroup.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
  libs/ui-lib/lib/ocm/components/ui/OcmFormFields.tsx
  libs/ui-lib/lib/ocm/hooks/useInfraEnvId.ts
  libs/ui-lib/lib/ocm/services/ClusterDetailsService.ts
  libs/ui-lib/lib/ocm/services/ClustersService.ts
  libs/ui-lib/lib/ocm/services/Day2ClusterService.ts
  libs/ui-lib/lib/ocm/services/types.ts
  libs/ui-lib/tsconfig.json
Labels: lgtm, size/XXL, jira/valid-reference

#2192 MGMT-14127: UI support for OCI platform (2.21)
  apps/assisted-ui/src/main.tsx
  libs/eslint-config-assisted-ui/index.js
  libs/ui-lib-tests/cypress/fixtures/storage/storage-cluster.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
  libs/ui-lib-tests/cypress/views/clusterDetails.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetailsForm.ts
  libs/ui-lib-tests/cypress/views/pages/NewClusterPage.ts
  libs/ui-lib/lib/common/api/swagger.yaml
  libs/ui-lib/lib/common/api/types.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/utils.ts
  libs/ui-lib/lib/common/components/clusterWizard/networkingSteps/VirtualIPControlGroup.tsx
  libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx
  libs/ui-lib/lib/common/components/ui/StaticTextField.tsx
  libs/ui-lib/lib/common/components/ui/formik/CheckboxField.tsx
  libs/ui-lib/lib/common/components/ui/formik/InputField.tsx
  libs/ui-lib/lib/common/components/ui/formik/RichInputField.tsx
  libs/ui-lib/lib/common/components/ui/formik/SelectField.tsx
  libs/ui-lib/lib/common/components/ui/formik/TextAreaField.tsx
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/common/features/featureGate.tsx
  libs/ui-lib/lib/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/CustomManifestCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/HostsNetworkConfigurationControlGroup.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmSingleNodeCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/VirtualIPControlGroup.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
  libs/ui-lib/lib/ocm/components/ui/OcmFormFields.tsx
  libs/ui-lib/lib/ocm/hooks/useInfraEnvId.ts
  libs/ui-lib/lib/ocm/services/ClusterDetailsService.ts
  libs/ui-lib/lib/ocm/services/ClustersService.ts
  libs/ui-lib/lib/ocm/services/Day2ClusterService.ts
  libs/ui-lib/lib/ocm/services/types.ts
  libs/ui-lib/tsconfig.json
Labels: lgtm, approved, size/XXL, jira/valid-reference

#2188 MGMT-14849: Changes in supported-platforms API with OCI
  libs/ui-lib/lib/common/types/clusters.ts
Labels: lgtm, size/XS, OCM, jira/valid-reference

#2189 MGMT-14849: Changes in supported-platforms API with OCI - 2.21
  libs/ui-lib/lib/common/types/clusters.ts
Labels: lgtm, approved, size/XS, OCM, jira/valid-reference

#2195 MGMT-14905: External platform integrations option should be available from OCP 4.14 and above
  libs/ui-lib/lib/common/types/featureSupportLevel.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/ExternalPartnerIntegrationsCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
  libs/ui-lib/lib/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts
Labels: lgtm, approved, size/L, jira/valid-reference

#2196 MGMT-14905: External platform integrations option should be available from OCP 4.14 and above
  libs/ui-lib/lib/common/types/featureSupportLevel.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/ExternalPartnerIntegrationsCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
  libs/ui-lib/lib/ocm/components/newFeatureSupportLevels/newFeatureStateUtils.ts
Labels: lgtm, size/L, jira/valid-reference

#2199 MGMT-14970: After node discovering not change cluster platform when platform type===oci
  libs/ui-lib/lib/ocm/components/clusterWizard/HostDiscovery.tsx
Labels: lgtm, size/S, OCM, jira/valid-reference

#2201 MGMT-14970: After node discovering not change cluster platform when platform type===oci - 2.21
  libs/ui-lib/lib/ocm/components/clusterWizard/HostDiscovery.tsx
Labels: lgtm, approved, size/S, OCM, jira/valid-reference

#2200 MGMT-14972: Full iso should be blocked in case of OCI (external partners)
  libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx
Labels: size/XS, OCM, jira/valid-reference

#2202 MGMT-14972: Full iso should be blocked in case of OCI (external partners) - 2.21
  libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageForm.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx
Labels: approved, size/XS, OCM, jira/valid-reference

#2203 MGMT-14543: Change full/minimal/ipxe description texts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx
Labels: lgtm, size/S, OCM, jira/valid-reference

#2198 MGMT-14833: On-Prem Day2 - add hosts button is not clickable
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetail.tsx
Labels: size/S, OCM, jira/valid-reference

#2205 MGMT-14833: On-Prem Day2 - add hosts button is not clickable - 2.21
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetail.tsx
Labels: lgtm, approved, size/S, OCM, jira/valid-reference

#2209 MGMT-14827: Remove multiarch capacity for UI - 2.21
  libs/ui-lib/lib/common/features/featureGate.tsx
Labels: lgtm, approved, size/XS, OCM, jira/valid-reference

#2212 MGMT-14996: Day 2 -Can't add hosts to SNO 4.14 cluster
  libs/ui-lib/lib/ocm/components/AddHosts/types.ts
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/utils.ts
  libs/ui-lib/lib/ocm/components/index.ts
  libs/ui-lib/lib/ocm/components/newFeatureSupportLevels/index.ts
  libs/ui-lib/lib/ocm/components/newFeatureSupportLevels/types.ts
  libs/ui-lib/lib/ocm/index.ts
  libs/ui-lib/lib/ocm/services/CpuArchitectureService.ts
  libs/ui-lib/lib/ocm/services/NewFeatureSupportLevelsService.ts
  libs/ui-lib/lib/ocm/services/apis/NewFeatureSupportLevelsAPI.ts
  libs/ui-lib/lib/ocm/services/apis/index.ts
  libs/ui-lib/lib/ocm/services/index.ts
Labels: lgtm, size/M, OCM, jira/valid-reference

#2213 MGMT-14996: Day 2 -Can't add hosts to SNO 4.14 cluster - 2.21
  libs/ui-lib/lib/ocm/components/AddHosts/types.ts
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/utils.ts
  libs/ui-lib/lib/ocm/components/index.ts
  libs/ui-lib/lib/ocm/components/newFeatureSupportLevels/index.ts
  libs/ui-lib/lib/ocm/components/newFeatureSupportLevels/types.ts
  libs/ui-lib/lib/ocm/index.ts
  libs/ui-lib/lib/ocm/services/CpuArchitectureService.ts
  libs/ui-lib/lib/ocm/services/NewFeatureSupportLevelsService.ts
  libs/ui-lib/lib/ocm/services/apis/NewFeatureSupportLevelsAPI.ts
  libs/ui-lib/lib/ocm/services/apis/index.ts
  libs/ui-lib/lib/ocm/services/index.ts
Labels: lgtm, approved, size/M, OCM, jira/valid-reference

#2215 Advance -> Advanced Typo
  libs/ui-lib/lib/ocm/components/clusterConfiguration/CustomManifestCheckbox.tsx
Labels: lgtm, size/XS

#2207 MGMT-14827: Remove multiarch capacity for UI
  libs/ui-lib/lib/common/features/featureGate.tsx
Labels: lgtm, size/XS, OCM, jira/valid-reference

#2194 MGMT-14842: In "Technology Preview" popover link doesn't open up URL
  libs/ui-lib/lib/common/components/ui/ExternalLink.tsx
Labels: size/S, OCM, jira/valid-reference

#2187 MGMT-14848: Enforce no-console eslint rule
  .eslintrc.json
  libs/eslint-config-assisted-ui/index.js
  libs/locales/lib/en/translation.json
  libs/locales/lib/ja/translation.json
  libs/locales/lib/ko/translation.json
  libs/locales/lib/zh/translation.json
  libs/ui-lib/lib/cim/components/Agent/MinimalHWRequirements.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentCredentials.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentKubeconfigDownload.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizardContext.tsx
  libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/HypershiftKubeconfigDownload.tsx
  libs/ui-lib/lib/cim/components/Hypershift/hooks/useSupportedOCPVersions.ts
  libs/ui-lib/lib/cim/components/featureSupportLevels/ACMFeatureSupportLevelProvider.tsx
  libs/ui-lib/lib/cim/components/helpers/network.ts
  libs/ui-lib/lib/cim/components/helpers/status.ts
  libs/ui-lib/lib/cim/components/modals/CimConfiguration/persist.ts
  libs/ui-lib/lib/cim/components/modals/EditBMHModal.tsx
  libs/ui-lib/lib/common/api/utils.ts
  libs/ui-lib/lib/common/components/clusterWizard/ReviewValidations.tsx
  libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts
  libs/ui-lib/lib/ocm/components/clusterDetail/RebootNodeZeroModal.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClustersTable.tsx
  libs/ui-lib/lib/ocm/sentry.ts
Labels: size/L, jira/valid-reference

#2193 MGMT-14787: Adding tests for events pagination
  libs/ui-lib-tests/cypress/fixtures/cluster/events.ts
  libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-updates.cy.ts
  libs/ui-lib-tests/cypress/integration/ui-behaviour/events-modal.cy.ts
  libs/ui-lib-tests/cypress/support/interceptors.ts
  libs/ui-lib-tests/cypress/views/modals/EventsModal.ts
  libs/ui-lib-tests/cypress/views/pages/ClusterPage.ts
  libs/ui-lib/lib/common/components/ui/ClusterEventsToolbar.tsx
  libs/ui-lib/lib/common/components/ui/eventsModal.tsx
Labels: lgtm, size/XL, OCM, jira/valid-reference

#2217 MGMT-14828: Fix icon of installed Day 2 host
  libs/ui-lib/lib/common/components/hosts/status.tsx
Labels: size/XS, jira/valid-reference

#2216 Improve setup documentation
  docs/CONTRIBUTING.md
  libs/ui-lib-tests/README.md
  package.json
Labels: size/S

#2204 MGMT-12202: Add MCE/ACM operator to the Assisted Installer wizard
  libs/locales/lib/en/translation.json
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-mce-operator.cy.ts
  libs/ui-lib-tests/cypress/views/common.ts
  libs/ui-lib-tests/cypress/views/forms/OperatorsForm.ts
  libs/ui-lib/lib/common/api/swagger.yaml
  libs/ui-lib/lib/common/api/types.ts
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/common/features/featureGate.tsx
  libs/ui-lib/lib/common/types/clusters.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/Operators.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
  libs/ui-lib/lib/ocm/services/OperatorsService.tsx
Labels: lgtm, size/L, OCM, jira/valid-reference

#2220 MGMT-14787: Fix flaky event pagination tests
  libs/ui-lib-tests/cypress/integration/ui-behaviour/events-modal.cy.ts
Labels: lgtm, size/S, OCM, jira/valid-reference

#2222 NO-ISSUE: Fix Prettier issues in VSCode
  .vscode/settings.json
Labels: size/XS, jira/valid-reference

#2221 Improving tests for MCE operator
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-mce-operator.cy.ts
  libs/ui-lib-tests/cypress/views/common.ts
Labels: size/XS, OCM

#2225 MGMT-14787: Event pagination test flakiness
  libs/ui-lib-tests/cypress/integration/ui-behaviour/events-modal.cy.ts
Labels: lgtm, size/L, jira/valid-reference

#2226 Introduce vitest for unit-testing
  .eslintrc.json
  .github/workflows/pull-request.yaml
  docs/CONTRIBUTING.md
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.test.ts
  libs/ui-lib/tsconfig.eslint.json
  libs/ui-lib/tsconfig.json
  package.json
  yarn.lock
Labels: size/XL

#2190 MGMT-14703: Limit and verify type when allowing to upload files / yaml to day2 [TESTS]
  .prettierignore
  libs/ui-lib-tests/cypress/fixtures/static-ip/files/img.png
  libs/ui-lib-tests/cypress/fixtures/static-ip/files/test.yaml
  libs/ui-lib-tests/cypress/fixtures/static-ip/index.ts
  libs/ui-lib-tests/cypress/fixtures/static-ip/static-network-config.ts
  libs/ui-lib-tests/cypress/integration/static-ip/3-configure-static-ip-yaml.cy.ts
  libs/ui-lib-tests/cypress/support/commands.ts
  libs/ui-lib-tests/cypress/support/variables/static-ip.ts
  libs/ui-lib-tests/cypress/views/staticIpPage.ts
  libs/ui-lib-tests/package.json
  libs/ui-lib-tests/tsconfig.json
  yarn.lock
Labels: size/L, OCM, jira/valid-reference

#2229 MGMT-15070: Unable to change machine-network when multiple interfaces
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/SubnetsDropdown.tsx
Labels: size/M, jira/valid-reference

#2218 MGMT-15046: Fix missing I18N
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Agent/AgentTable.tsx
  libs/ui-lib/lib/cim/components/Agent/AgentsSelectionTable.tsx
  libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
  libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsTable.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostDiscoveryTable.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvAgentTable.tsx
  libs/ui-lib/lib/common/components/hosts/tableUtils.tsx
  libs/ui-lib/lib/ocm/components/hosts/ClusterHostsTable.tsx
  libs/ui-lib/lib/ocm/components/hosts/HostsDiscoveryTable.tsx
  libs/ui-lib/lib/ocm/components/hosts/HostsStorageTable.tsx
Labels: size/M, jira/valid-reference

#2230 MGMT-14576: Fix noProxy validation
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.test.ts
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
Labels: size/M, jira/valid-reference

#2191 MGMT-14717: Adding tests for custom manifests step
  .prettierignore
  libs/ui-lib-tests/cypress/@types/Cypress.d.ts
  libs/ui-lib-tests/cypress/fixtures/custom-manifests/1-cluster-created.ts
  libs/ui-lib-tests/cypress/fixtures/custom-manifests/files/img.png
  libs/ui-lib-tests/cypress/fixtures/custom-manifests/files/manifest1.yaml
  libs/ui-lib-tests/cypress/fixtures/custom-manifests/index.ts
  libs/ui-lib-tests/cypress/fixtures/custom-manifests/manifests.ts
  libs/ui-lib-tests/cypress/integration/custom-manifests/1-create-cluster-with-custom-manifests.cy.ts
  libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts
  libs/ui-lib-tests/cypress/integration/custom-manifests/3-removing-adding-custom-manifests.cy.ts
  libs/ui-lib-tests/cypress/integration/custom-manifests/4-view-custom-manifests-review-and-create-page.cy.ts
  libs/ui-lib-tests/cypress/support/interceptors.ts
  libs/ui-lib-tests/cypress/views/clusterDetails.ts
  libs/ui-lib-tests/cypress/views/common.ts
  libs/ui-lib-tests/cypress/views/customManifestsPage.ts
  libs/ui-lib-tests/cypress/views/reviewCreate.ts
  libs/ui-lib/lib/common/components/ui/formik/CodeField.tsx
  libs/ui-lib/lib/common/components/ui/formik/types.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifest.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/ExpandedManifest.tsx
Labels: size/L, OCM, jira/valid-reference

#2234 Remove unnecessary fallback for sched masters
  libs/ui-lib-tests/cypress/fixtures/cluster/base-cluster.ts
  libs/ui-lib-tests/cypress/fixtures/storage/storage-cluster.ts
  libs/ui-lib/lib/common/selectors/clusterSelectors.ts
Labels: size/S

#2236 Improve text assertions
  libs/ui-lib-tests/cypress/integration/create-multinode/0-create-cluster.cy.ts
  libs/ui-lib-tests/cypress/integration/create-multinode/1-host-discovery.cy.ts
  libs/ui-lib-tests/cypress/integration/create-multinode/3-review.cy.ts
  libs/ui-lib-tests/cypress/integration/create-sno/0-create-cluster.cy.ts
  libs/ui-lib-tests/cypress/integration/create-sno/1-host-discovery.cy.ts
  libs/ui-lib-tests/cypress/integration/create-sno/3-review.cy.ts
  libs/ui-lib-tests/cypress/integration/custom-manifests/1-create-cluster-with-custom-manifests.cy.ts
  libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts
  libs/ui-lib-tests/cypress/integration/custom-manifests/4-view-custom-manifests-review-and-create-page.cy.ts
  libs/ui-lib-tests/cypress/integration/dualstack/3-review.cy.ts
  libs/ui-lib-tests/cypress/integration/features/disk-encryption.cy.ts
  libs/ui-lib-tests/cypress/integration/static-ip/0-create-cluster.cy.ts
  libs/ui-lib-tests/cypress/integration/static-ip/3-configure-static-ip-yaml.cy.ts
  libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-creation.cy.ts
  libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-updates.cy.ts
  libs/ui-lib-tests/cypress/support/variables/storage-step.ts
  libs/ui-lib-tests/cypress/views/bareMetalDiscovery.ts
  libs/ui-lib-tests/cypress/views/bareMetalDiscoveryIsoModal.ts
  libs/ui-lib-tests/cypress/views/clusterDetails.ts
  libs/ui-lib-tests/cypress/views/clusterList.ts
  libs/ui-lib-tests/cypress/views/common.ts
  libs/ui-lib-tests/cypress/views/hostsTableSection.ts
  libs/ui-lib-tests/cypress/views/installationPage.ts
  libs/ui-lib-tests/cypress/views/networkingPage.ts
  libs/ui-lib-tests/cypress/views/reviewCreate.ts
  libs/ui-lib-tests/cypress/views/storagePage.ts
Labels: lgtm, size/L
