Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2024-05, with the labels that each got.

#2572 MGMT-17706: Handle missing message/reason fields in resource conditions
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/ConditionsTable.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/EnvironmentErrors.tsx
  libs/ui-lib/lib/cim/components/common/ResourceAlerts.tsx
  libs/ui-lib/lib/cim/components/helpers/status.ts
  libs/ui-lib/lib/cim/types/k8s/shared.ts
Labels: lgtm, size/L, jira/valid-reference

#2573 [v2.10-cim] MGMT-17706: Handle missing message/reason fields in resource conditions
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/ConditionsTable.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/EnvironmentErrors.tsx
  libs/ui-lib/lib/cim/components/common/ResourceAlerts.tsx
  libs/ui-lib/lib/cim/components/helpers/status.ts
  libs/ui-lib/lib/cim/types/k8s/shared.ts
Labels: lgtm, size/L, jira/valid-reference

#2568 MGMT-16476: Validate that user consent about SNO limitations before create the cluster
  libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
  libs/ui-lib/lib/ocm/services/ClusterDetailsService.ts
  libs/ui-lib/lib/ocm/services/types.ts
Labels: size/S, OCM

#2566 MGMT-17122: Change reason in helper for disabled operators when nutanix platform is selected
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
Labels: size/S, OCM, jira/valid-reference

#2570 MGMT-16985: Not allow to remove nodes in day2 cluster
  libs/ui-lib/lib/common/components/hosts/utils.ts
Labels: size/XS, OCM, jira/valid-reference

#2574 NO-ISSUE: Fix Github actions to deploy Assisted UI lib
  apps/assisted-ui/Containerfile
Labels: size/XS, jira/valid-reference

#2576 MGMT-8534: Adjusting UI documentation links to OCP version selected
  libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionMode.tsx
  libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
  libs/ui-lib/lib/common/components/hosts/types.ts
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
  libs/ui-lib/lib/ocm/components/hosts/HardwareStatus.tsx
  libs/ui-lib/lib/ocm/components/hosts/HostsDiscoveryTable.tsx
Labels: lgtm, size/L, OCM, jira/valid-reference

#2577 MGMT-17696: Show an error message to the user when the cluster preparation fails
  libs/ui-lib/lib/common/components/clusterWizard/ClusterWizardStepValidationsAlert.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardFooter.tsx
Labels: lgtm, size/S, OCM, jira/valid-reference

#2569 NO-ISSUE Use ReactDOM 18 functions
  apps/assisted-ui/src/main.tsx
  libs/ui-lib/lib/_test-helpers/mock-container.ts
  libs/ui-lib/lib/common/components/ui/formik/LabelField.tsx
  libs/ui-lib/lib/ocm/hooks/_use-feature-detection.test.tsx
  libs/ui-lib/package.json
  yarn.lock
Labels: size/XXL

#2575 MGMT-15977: Add warning alert for soft installation timeouts
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/ProgressBarAlerts.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/getProgressBarAlerts.tsx
Labels: size/M, OCM, jira/valid-reference

#2579 MGMT-17851: Assisted Installer link documentation is broken
  libs/ui-lib/lib/common/config/constants.ts
Labels: lgtm, size/XS, OCM, jira/valid-reference

#2581 MGMT-17439: Add tests to assisted-ui-lib for custom OCP releases - 2.31
  libs/ui-lib-tests/cypress/integration/custom-manifests/3-removing-adding-custom-manifests.cy.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-custom-ocp-releases.cy.ts
  libs/ui-lib-tests/cypress/views/clusterDetails.ts
  libs/ui-lib-tests/cypress/views/customOCPModal.ts
Labels: size/L, OCM, jira/valid-reference

#2580 MGMT-17851: Asisted installer link documentation broken - 2.31
  libs/ui-lib/lib/common/config/constants.ts
Labels: size/XS, OCM, jira/valid-reference

#2578 MGMT-17206: Add information to hosts inventory table about host stage timeout in Installation page
  libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/HostInventoryExpandable.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/utils.tsx
Labels: size/M, OCM, jira/valid-reference

#2582 MGMT-17904: Custom manifests page - UI not validating filename field before sending it to BE
  libs/ui-lib-tests/cypress/integration/custom-manifests/3-removing-adding-custom-manifests.cy.ts
  libs/ui-lib-tests/cypress/views/forms/CustomManifests/CustomManifestsForm.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx
Labels: size/L, jira/valid-reference

#2583 MGMT-17904: Custom manifests page - UI not validating filename field before sending it to BE - 2.31
  libs/ui-lib-tests/cypress/integration/custom-manifests/3-removing-adding-custom-manifests.cy.ts
  libs/ui-lib-tests/cypress/views/forms/CustomManifests/CustomManifestsForm.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx
Labels: size/L, OCM, jira/valid-reference

#2584 MGMT-17933: Create docs_links file with all documentation links
  libs/ui-lib/lib/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/DiscoveryTroubleshootingModal.tsx
  libs/ui-lib/lib/common/components/hosts/HostRequirements.tsx
  libs/ui-lib/lib/common/components/ui/TechnologyPreview.tsx
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/common/config/docs_links.ts
  libs/ui-lib/lib/common/config/index.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/UserManagedNetworkingTextContent.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx
  libs/ui-lib/lib/ocm/components/hosts/HostRequirementsContent.tsx
Labels: lgtm, size/L, OCM, jira/valid-reference

#2586 MGMT-17804: Change validation for patch manifests
  libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts
  libs/ui-lib/lib/common/utils.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx
Labels: lgtm, size/S, OCM, jira/valid-reference

#2587 MGMT-17955: Show the correct icon next to the nodes
  libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
Labels: lgtm, size/XS, OCM, jira/valid-reference

#2588 MGMT-17955: Show the correct icon next to the nodes - 2.32
  libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
Labels: lgtm, size/XS, jira/valid-reference

#2589 MGMT-17417 Consider architecture label when getting ocp img arch
  libs/ui-lib/lib/cim/components/helpers/versions.ts
Labels: lgtm, size/S

#2590 [2.10-cim] MGMT-17417 Consider architecture label when getting ocp img arch
  libs/ui-lib/lib/cim/components/helpers/versions.ts
Labels: lgtm, size/S
