Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2024-08, with the labels that each got.

#2637 MGMT-17147: Update openshift-assisted/ui-lib to react-router-dom v6
  apps/assisted-ui/package.json
  apps/assisted-ui/src/components/App.tsx
  libs/ui-lib/lib/cim/components/Agent/NoAgentsAlert.tsx
  libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
  libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/NodePoolsTable.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/AddHostDropdown.tsx
  libs/ui-lib/lib/cim/components/modals/CimConfiguration/CimConfigProgressAlert.tsx
  libs/ui-lib/lib/cim/components/modals/CimConfiguration/CimStorageMissingAlert.tsx
  libs/ui-lib/lib/cim/components/modals/MassDeleteAgentModal.tsx
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabMock.tsx
  libs/ui-lib/lib/ocm/components/Routes.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetail.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardContextProvider.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardFooter.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/Operators.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterBreadcrumbs.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterPageErrors.tsx
  libs/ui-lib/lib/ocm/components/clusters/Clusters.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClustersListToolbar.tsx
  libs/ui-lib/lib/ocm/components/clusters/NewClusterPage.tsx
  libs/ui-lib/lib/ocm/components/ui/Buttons/BackButton.tsx
  libs/ui-lib/lib/ocm/components/ui/RedirectToCluster.tsx
  libs/ui-lib/lib/ocm/config/constants.ts
  libs/ui-lib/lib/ocm/store/slices/clusters/selectors.tsx
  libs/ui-lib/package.json
  yarn.lock
Labels: lgtm, size/L, jira/valid-reference

#2647 MGMT-18099: Warning of error in prepare installation remain even after fixing manifest name
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/CustomManifestsForm.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/utils.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/data/dataTypes.ts
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardContextProvider.tsx
Labels: size/S, jira/valid-reference

#2648 MGMT-16745: Add platform field to R&C and installation pages
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewPlatformTable.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewSummary.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/index.tsx
Labels: size/M, jira/valid-reference

#2651 MGMT-18567: Solving errors in clusters list
  libs/ui-lib/lib/ocm/components/clusters/ClustersListToolbar.tsx
Labels: size/XS, OCM, jira/valid-reference

#2650 MGMT-18567: Solving errors in clusters list - 2.33
  libs/ui-lib/lib/ocm/components/clusters/ClustersListToolbar.tsx
  libs/ui-lib/lib/ocm/components/clusters/CustomToolbarFilter.tsx
Labels: lgtm, size/L, OCM, jira/valid-reference

#2652 MGMT-18567: Solving errors in clusters list
  libs/ui-lib/lib/ocm/components/clusters/ClustersListToolbar.tsx
  libs/ui-lib/lib/ocm/components/clusters/CustomToolbarFilter.tsx
Labels: lgtm, size/L, OCM, jira/valid-reference

#2654 MGMT-18567: Solving errors in clusters list
  libs/ui-lib/lib/ocm/components/clusters/ClustersListToolbar.tsx
  libs/ui-lib/lib/ocm/components/clusters/CustomToolbarFilter.tsx
Labels: lgtm, size/L, jira/valid-reference

#2656 NO-ISSUE: Work with OCM-UI router v6 ugprade
  libs/ui-lib-tests/cypress/integration/create-multinode/0-create-cluster.cy.ts
  libs/ui-lib-tests/cypress/integration/create-sno/0-create-cluster.cy.ts
  libs/ui-lib-tests/cypress/integration/static-ip/0-create-cluster.cy.ts
  libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-creation.cy.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-custom-ocp-releases.cy.ts
  libs/ui-lib-tests/cypress/support/variables/cluster-details.ts
  libs/ui-lib-tests/cypress/views/common.ts
  libs/ui-lib-tests/cypress/views/pages/ClusterPage.ts
  libs/ui-lib-tests/cypress/views/pages/NewClusterPage.ts
  libs/ui-lib/lib/ocm/components/Routes.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterBreadcrumbs.tsx
  libs/ui-lib/package.json
  yarn.lock
Labels: size/M, jira/valid-reference
