Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2024-01, with the labels that each got.

#2423 MGMT-15365: It's possible to attempt to delete a host from infraenv for a standalone cluster created by integrated UI flow
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
Labels: size/S, jira/valid-reference

#2442 MGMT-16284: Infrastructure->Host Inventory->Hosts : Actions menu tooltip is unmarked for translation
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/common/components/hosts/TableToolbar.tsx
Labels: size/XS, jira/valid-reference

#2430 MGMT-15791: Its not clear when is the boot mac address required
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
Labels: size/XS, jira/valid-reference

#2439 MGMT-16195 Enable switching from Single replica to HA
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsForm.tsx
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsStep.tsx
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/types.ts
Labels: size/M

#2463 MGMT-15633: Improve UX for static network config in CIM (in BMC dialog) [BACKPORT 2.8]
  libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
Labels: lgtm, size/S, jira/valid-reference

#2459 MGMT-15365: It's possible to attempt to delete a host from infraenv for a standalone cluster created by integrated UI flow [BACKPORT 2.8]
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
Labels: size/S, jira/valid-reference

#2462 MGMT-16195 Enable switching from Single replica to HA [BACKPORT 2.9]
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsForm.tsx
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsStep.tsx
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/types.ts
Labels: size/M

#2464 MGMT-15633: Improve UX for static network config in CIM (in BMC dialog) [BACKPORT 2.9]
  libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
Labels: size/S, jira/valid-reference

#2460 MGMT-15365: It's possible to attempt to delete a host from infraenv for a standalone cluster created by integrated UI flow [BACKPORT 2.9]
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
Labels: size/S, jira/valid-reference

#2456 MGMT-16390: Change popup text about the usage of multiple ssh keys
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx
Labels: size/S, jira/valid-reference

#2466 MGMT-16480: Remove what's new link outside OCM because does not work
  libs/ui-lib/lib/ocm/components/clusters/AssistedInstallerHeader.tsx
Labels: size/S, OCM, jira/valid-reference

#2467 MGMT-16481: Add developer preview badge in external platform integration dropdown when platform is dev-preview
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
Labels: size/S, OCM, jira/valid-reference

#2468 MGMT-16478: Solving problems creating ARM+4.10 cluster
  libs/ui-lib/lib/ocm/services/ClusterDetailsService.ts
Labels: size/XS, OCM, jira/valid-reference

#2469 MGMT-16475: Change reason for platform dropdown to be disabled
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
Labels: size/S, OCM, jira/valid-reference

#2471 PreviewBadge: Disable focustrap
  libs/ui-lib/lib/common/components/ui/PreviewBadge.tsx
Labels: size/XS

#2474 MGMT-16558: Failed messages not cleaned after download cluster installation logs
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterInstallationError.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/ProgressBarAlerts.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/utils.tsx
Labels: lgtm, size/S, OCM, jira/valid-reference

#2475 MGMT-16558: Failed messages not cleaned after download cluster installation logs - 2.30
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterInstallationError.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/ProgressBarAlerts.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/utils.tsx
Labels: lgtm, size/S, OCM, jira/valid-reference

#2481 NO-ISSUE: Change latest-released tag for staging-released tag in UI released
  .github/workflows/push-to-master.yaml
Labels: lgtm, size/XS, jira/valid-reference

#2479 MGMT-16387: Disable SDN option in OCP version > 4.15
  libs/types/assisted-installer-service.d.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
Labels: size/M, OCM, jira/valid-reference

#2484 MGMT-16463: Enable LVMS for OCP version 4.15 or above
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
  libs/ui-lib/lib/ocm/components/utils.ts
Labels: lgtm, size/M, OCM, jira/valid-reference

#2485 MGMT-16463: Enable LVMS for OCP version 4.15 or above - 2.30
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
  libs/ui-lib/lib/ocm/components/utils.ts
Labels: lgtm, size/M, OCM, jira/valid-reference

#2449 MGMT-16297: CIM translations
  libs/locales/lib/en/translation.json
  libs/locales/lib/ja/translation.json
  libs/locales/lib/ko/translation.json
  libs/locales/lib/zh/translation.json
  libs/ui-lib/lib/cim/components/Agent/AgentStatus.tsx
  libs/ui-lib/lib/cim/components/Agent/AgentTable.tsx
  libs/ui-lib/lib/cim/components/Agent/AgentsSelectionTable.tsx
  libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsTable.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostDiscoveryTable.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostsNetworkTable.tsx
  libs/ui-lib/lib/cim/components/Hypershift/utils/status.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvAgentTable.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvHostsTabAgentsWarning.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraTableToolbar.tsx
  libs/ui-lib/lib/cim/components/helpers/agentStatus.tsx
  libs/ui-lib/lib/cim/components/helpers/agents.ts
  libs/ui-lib/lib/cim/components/helpers/status.ts
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
  libs/ui-lib/lib/cim/components/modals/MassApproveAgentModal.tsx
  libs/ui-lib/lib/cim/components/modals/MassDeleteAgentModal.tsx
  libs/ui-lib/lib/common/components/clusterWizard/networkingSteps/ManagedNetworkingControlGroup.tsx
  libs/ui-lib/lib/common/components/hosts/HostRowDetail.tsx
  libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
  libs/ui-lib/lib/common/components/hosts/status.tsx
  libs/ui-lib/lib/common/components/hosts/tableUtils.tsx
  libs/ui-lib/lib/common/components/storage/DisksTable.tsx
  libs/ui-lib/lib/common/components/storage/StorageDetail.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationTableBase.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/HostInventoryExpandable.tsx
  libs/ui-lib/lib/ocm/components/hosts/HardwareStatus.tsx
  libs/ui-lib/lib/ocm/components/hosts/NetworkingStatus.tsx
Labels: lgtm, size/XXL, jira/valid-reference

#2465 MGMT-16297: CIM translations [BACKPORT 2.9]
  libs/locales/lib/en/translation.json
  libs/locales/lib/ja/translation.json
  libs/locales/lib/ko/translation.json
  libs/locales/lib/zh/translation.json
  libs/ui-lib/lib/cim/components/Agent/AgentStatus.tsx
  libs/ui-lib/lib/cim/components/Agent/AgentTable.tsx
  libs/ui-lib/lib/cim/components/Agent/AgentsSelectionTable.tsx
  libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsTable.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostDiscoveryTable.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostsNetworkTable.tsx
  libs/ui-lib/lib/cim/components/Hypershift/utils/status.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvAgentTable.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvHostsTabAgentsWarning.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraTableToolbar.tsx
  libs/ui-lib/lib/cim/components/helpers/agentStatus.tsx
  libs/ui-lib/lib/cim/components/helpers/agents.ts
  libs/ui-lib/lib/cim/components/helpers/status.ts
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
  libs/ui-lib/lib/cim/components/modals/MassApproveAgentModal.tsx
  libs/ui-lib/lib/cim/components/modals/MassDeleteAgentModal.tsx
  libs/ui-lib/lib/common/components/clusterWizard/networkingSteps/ManagedNetworkingControlGroup.tsx
  libs/ui-lib/lib/common/components/hosts/HostRowDetail.tsx
  libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
  libs/ui-lib/lib/common/components/hosts/status.tsx
  libs/ui-lib/lib/common/components/hosts/tableUtils.tsx
  libs/ui-lib/lib/common/components/storage/DisksTable.tsx
  libs/ui-lib/lib/common/components/storage/StorageDetail.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationTableBase.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/HostInventoryExpandable.tsx
  libs/ui-lib/lib/ocm/components/hosts/HardwareStatus.tsx
  libs/ui-lib/lib/ocm/components/hosts/NetworkingStatus.tsx
Labels: lgtm, size/XXL, jira/valid-reference

#2441 MGMT-15633: Improve UX for static network config in CIM (in BMC dialog)
  libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
Labels: size/S, jira/valid-reference

#2488 MGMT-15365: It's possible to attempt to delete a host from infraenv for a standalone cluster created by integrated UI flow [FOLLOWUP] [BACKPORT 2.9]
  libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
Labels: size/XS, jira/valid-reference

#2486 MGMT-16645: Add preview badge inside external platform integration dropdown depeding feature support level of each platform
  libs/ui-lib-tests/cypress/fixtures/infra-envs/feature-support.ts
  libs/ui-lib-tests/cypress/fixtures/infra-envs/openshift-versions.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetails/Fields/ExternalPartnerIntegrationsField.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
Labels: lgtm, size/M, OCM, jira/valid-reference

#2489 MGMT-16645: Add preview badge inside external platform integration dropdown depeding feature support level of each platform - 2.30
  libs/ui-lib-tests/cypress/fixtures/infra-envs/feature-support.ts
  libs/ui-lib-tests/cypress/fixtures/infra-envs/openshift-versions.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetails/Fields/ExternalPartnerIntegrationsField.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
Labels: lgtm, size/M, jira/valid-reference
