Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2024-07, with the labels that each got.

#2627 MGMT-18241: Change documentation link for LVMS operator
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: lgtm, size/XS, jira/valid-reference

#2628 MGMT-18241: Change documentation link for LVMS operator - 2.32
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: lgtm, size/XS, OCM, jira/valid-reference

#2625 MGMT-17466: There is no way to Abort cluster installation when it is Finalizing
  libs/ui-lib/lib/ocm/components/clusterDetail/CancelInstallationModal.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.tsx
Labels: size/XS, jira/valid-reference

#2626 MGMT-17388: Log string literal format shown with "special" characters
  libs/ui-lib/lib/common/components/ui/EventsList.tsx
Labels: size/XS, jira/valid-reference

#2629 MGMT-18296: User Managed networking selection in Network page is not "remembered"
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfiguration.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/networkConfigurationValidation.ts
Labels: size/S, jira/valid-reference

#2631 MGMT-18321: Change Assisted Installer documentation link
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: lgtm, size/XS, OCM, jira/valid-reference

#2632 MGMT-17540: Remove unnecessary calls to openshift-versions API in cluster creation page
  libs/ui-lib/lib/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabMock.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmOpenShiftVersionSelect.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OpenShiftVersionModal.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewPreflightChecks.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/OpenShiftVersionDetail.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OpenshiftVersionsContext.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx
  libs/ui-lib/lib/ocm/components/clusters/NewClusterPage.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx
  libs/ui-lib/lib/ocm/hooks/index.ts
  libs/ui-lib/lib/ocm/hooks/useOpenshiftVersions.tsx
Labels: size/L, jira/valid-reference

#2634 MGMT-18358: Clear alerts when change from one view to another in Static network configurations step
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/StaticIpViewRadioGroup.tsx
Labels: lgtm, size/XS, OCM, jira/valid-reference

#2633 MGMT-18357: Change alignment of MacIpMapping fields in Static Network Configuration
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/YamlView/MacIpMapping.tsx
Labels: size/S, OCM, jira/valid-reference

#2635 MGMT-18368: Removable field 'remove' button styling issues
  libs/ui-lib/lib/common/components/ui/formik/RemovableField.css
Labels: lgtm, size/S, jira/valid-reference

#2592 NO-ISSUE: Adapting code for decoupling tasks
  libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterBreadcrumbs.tsx
  libs/ui-lib/lib/ocm/components/ui/Buttons/BackButton.tsx
Labels: size/M, jira/valid-reference

#2639 MGMT-17540: Remove unnecessary calls to openshift-versions API in cluster creation page [FOLLOWUP, BACKPORT 2.33]
  libs/ui-lib-tests/cypress/integration/day-2/1-first-access.cy.ts
  libs/ui-lib-tests/cypress/support/interceptors.ts
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerExtraDetailCard.tsx
Labels: lgtm, size/M, jira/valid-reference

#2638 MGMT-17540: Remove unnecessary calls to openshift-versions API in cluster creation page [FOLLOWUP]
  libs/ui-lib-tests/cypress/integration/day-2/1-first-access.cy.ts
  libs/ui-lib-tests/cypress/support/interceptors.ts
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerExtraDetailCard.tsx
Labels: lgtm, size/M, jira/valid-reference

#2640 NO-ISSUE: Updating monaco-editor library to use in assisted-installer-app
  apps/assisted-ui/package.json
  libs/ui-lib/package.json
  yarn.lock
Labels: size/S, jira/valid-reference

#2641 Updating monaco-editor lib - 2.33
  apps/assisted-ui/package.json
  libs/ui-lib/package.json
  yarn.lock
Labels: size/S, OCM

#2643 MGMT-18439: Handle undefined majority_groups gracefully
  libs/ui-lib/lib/cim/components/helpers/network.ts
Labels: lgtm, size/XS, jira/valid-reference

#2646 MGMT-18439: Handle undefined majority_groups gracefully [BACKPORT 2.12]
  libs/ui-lib/lib/cim/components/helpers/network.ts
Labels: lgtm, size/XS, jira/valid-reference

#2644 MGMT-18429: Removing ASSISTED_INSTALLER_PLATFORM_OCI feature flag
  libs/ui-lib/lib/common/features/featureGate.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
  libs/ui-lib/lib/ocm/config/external-features.ts
  libs/ui-lib/lib/ocm/hooks/_use-feature-detection.test.tsx
  libs/ui-lib/lib/ocm/store/slices/feature-flags/slice.ts
Labels: size/M, OCM, jira/valid-reference
