Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2024-03, with the labels that each got.

#2508 MGMT-17013: Solving problems with icon's color that are incorrect in Review&Create page
  libs/ui-lib-tests/cypress/views/storagePage.ts
  libs/ui-lib/lib/cim/components/Agent/MinimalHWRequirements.tsx
  libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/ConditionsTable.tsx
  libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/HostedClusterProgress.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/DiscoveryTroubleshootingModal.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx
  libs/ui-lib/lib/common/components/clusterWizard/ReviewValidations.tsx
  libs/ui-lib/lib/common/components/hosts/VMRebootConfigurationInfo.tsx
  libs/ui-lib/lib/common/components/storage/DisksTable.tsx
  libs/ui-lib/lib/common/components/storage/StorageUtils.tsx
  libs/ui-lib/lib/common/components/ui/UiIcon.tsx
  libs/ui-lib/lib/common/components/ui/WizardNavItem.tsx
  libs/ui-lib/lib/common/components/ui/formik/RemovableField.tsx
  libs/ui-lib/lib/common/components/ui/index.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmOpenShiftVersionSelect.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/PlatformIntegrationNote.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewPreflightChecks.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/OpenShiftVersionDetail.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/ResetClusterModal.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterStatus.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx
  libs/ui-lib/lib/ocm/components/ui/InfoLinkWithModal.tsx
Labels: lgtm, size/L, OCM, jira/valid-reference

#2513 MGMT-17107: Update operators checkbox when cluster ready exits from cluster window when we are in 'Overview' tab inside OCM
  libs/ui-lib/lib/ocm/components/clusterWizard/Operators.tsx
Labels: lgtm, size/XS, OCM, jira/valid-reference

#2507 MGMT-16970: BMH status not updated in console during provisioning phase
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvAgentTable.tsx
Labels: size/S, jira/valid-reference

#2511 MGMT-16982: Enable switching infra-availability-policy Single replica / HA
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsForm.tsx
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsStep.tsx
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/types.ts
Labels: size/M, jira/valid-reference

#2512 MGMT-16982: Enable switching infra-availability-policy Single replica / HA [BACKPORT 2.10]
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsForm.tsx
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/HostsStep.tsx
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/HostsStep/types.ts
Labels: lgtm, size/M, jira/valid-reference

#2514 MGMT-16970: BMH status not updated in console during provisioning phase [BACKPORT 2.10]
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvAgentTable.tsx
Labels: size/S, jira/valid-reference

#2517 MGMT-17130: Add correct id to <HelperItem> components when shown errors
  libs/ui-lib-tests/cypress/integration/static-ip/1-configure-static-ip-network-wide.cy.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/validations-new-cluster-page.cy.ts
  libs/ui-lib-tests/cypress/support/variables/cluster-details.ts
  libs/ui-lib-tests/cypress/views/clusterDetails.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/SecurityFields.tsx
  libs/ui-lib/lib/common/components/ui/StaticTextField.tsx
  libs/ui-lib/lib/common/components/ui/formik/CertificatesUploadField.tsx
  libs/ui-lib/lib/common/components/ui/formik/CheckboxField.tsx
  libs/ui-lib/lib/common/components/ui/formik/CodeField.tsx
  libs/ui-lib/lib/common/components/ui/formik/InputField.tsx
  libs/ui-lib/lib/common/components/ui/formik/LabelField.tsx
  libs/ui-lib/lib/common/components/ui/formik/MultiSelectField.tsx
  libs/ui-lib/lib/common/components/ui/formik/NumberInputField.tsx
  libs/ui-lib/lib/common/components/ui/formik/RichInputField.tsx
  libs/ui-lib/lib/common/components/ui/formik/SelectField.tsx
  libs/ui-lib/lib/common/components/ui/formik/SwitchField.tsx
  libs/ui-lib/lib/common/components/ui/formik/TextAreaField.tsx
  libs/ui-lib/lib/common/components/ui/formik/UploadField.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/FormViewNetworkWide/FormViewNetworkWideFields.tsx
Labels: lgtm, size/L, OCM, jira/valid-reference

#2518 MGMT-17155: Remove error helper duplicated in SecurityFields in Networking Page
  libs/ui-lib/lib/common/components/clusterConfiguration/SecurityFields.tsx
Labels: size/S, OCM, jira/valid-reference

#2519 MGMT-17132: Trigger SSH key validations when user changes this field
  libs/ui-lib/lib/common/components/ui/formik/UploadField.tsx
Labels: size/S, OCM, jira/valid-reference

#2516 MGMT-17121: Cluster name show validation message when typing characters
  apps/assisted-ui/package.json
  libs/ui-lib-tests/package.json
  libs/ui-lib/lib/common/components/clusterConfiguration/DownloadIpxeScript.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/DownloadIso.tsx
  libs/ui-lib/lib/common/components/ui/PrismCode.tsx
  libs/ui-lib/lib/common/components/ui/formik/RichInputField.tsx
  libs/ui-lib/package.json
  yarn.lock
Labels: size/L, OCM, jira/valid-reference

#2520 MGMT-17236: Add aria label property to close button in host status popover to help cypress tests
  libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
Labels: size/XS, OCM, jira/valid-reference

#2515 MGMT-17118: Host agent name change, UX flow could be improved
  libs/ui-lib/lib/cim/components/modals/EditAgentModal.tsx
Labels: size/XS, jira/valid-reference

#2522 MGMT-17281: CIM UI crashes if the installation_disk_id is not correct
  libs/ui-lib/lib/cim/components/helpers/agentStatus.tsx
  libs/ui-lib/lib/cim/components/helpers/status.ts
Labels: lgtm, size/XS, jira/valid-reference

#2523 MGMT-17281: CIM UI crashes if the installation_disk_id is not correct [BACKPORT 2.9]
  libs/ui-lib/lib/cim/components/helpers/agentStatus.tsx
  libs/ui-lib/lib/cim/components/helpers/status.ts
Labels: lgtm, size/XS, jira/valid-reference

#2524 MGMT-17281: CIM UI crashes if the installation_disk_id is not correct [BACKPORT 2.10]
  libs/ui-lib/lib/cim/components/helpers/agentStatus.tsx
  libs/ui-lib/lib/cim/components/helpers/status.ts
Labels: lgtm, size/XS, jira/valid-reference

#2526 MGMT-17236: Add aria label property to close button in host status popover to help cypress tests - 2.31
  libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
Labels: lgtm, size/XS, jira/valid-reference

#2528 MGMT-17121: Cluster name show validation message when typing characters - 2.31
  apps/assisted-ui/package.json
  libs/ui-lib-tests/package.json
  libs/ui-lib/lib/common/components/clusterConfiguration/DownloadIpxeScript.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/DownloadIso.tsx
  libs/ui-lib/lib/common/components/ui/PrismCode.tsx
  libs/ui-lib/lib/common/components/ui/formik/RichInputField.tsx
  libs/ui-lib/package.json
  yarn.lock
Labels: size/L, jira/valid-reference

#2529 MGMT-17132: Trigger SSH key validations when user changes this field - 2.31
  libs/ui-lib/lib/common/components/ui/formik/UploadField.tsx
Labels: size/S, jira/valid-reference

#2530 MGMT-15999: Assisted Installer UI should allow patch manifests
  libs/types/assisted-installer-service.d.ts
  libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts
  libs/ui-lib/lib/common/utils.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx
Labels: lgtm, size/M, OCM, jira/valid-reference

#2531 MGMT-15999: Assisted Installer UI should allow patch manifests - 2.31
  libs/types/assisted-installer-service.d.ts
  libs/ui-lib-tests/cypress/integration/custom-manifests/2-modifying-existing-custom-manifest.cy.ts
  libs/ui-lib/lib/common/utils.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/customManifestsValidationSchema.tsx
Labels: size/M, OCM, jira/valid-reference
