Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2024-06, with the labels that each got.

#2585 MGMT-17940: CIM UI crashes on the create cluster networking page
  libs/ui-lib/lib/cim/components/helpers/network.ts
Labels: size/S, jira/valid-reference

#2591 Add host popup - proxy fields - API supports adding one of the proxy fields while in UI both HTTP and HTTPS are mandatory
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmDiscoveryImageConfigForm.tsx
Labels: lgtm, size/XS

#2593 MGMT-16841: Failed to add host when infraenv has networkType of DHCP [BACKPORT 2.9]
  libs/ui-lib/lib/cim/components/Agent/BMCForm.tsx
Labels: lgtm, size/M, jira/valid-reference

#2594 MGMT-17118: Host agent name change, UX flow could be improved [BACKPORT 2.11]
  libs/ui-lib/lib/cim/components/modals/EditAgentModal.tsx
Labels: lgtm, size/XS, jira/valid-reference

#2595 MGMT-17940: CIM UI crashes on the create cluster networking page [BACKPORT 2.11]
  libs/ui-lib/lib/cim/components/helpers/network.ts
Labels: size/S, jira/valid-reference

#2596 MGMT-18050: UI warning icon not changed to error icon on 24 hours timeout in hosts table
  libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
Labels: lgtm, size/S, OCM, jira/valid-reference

#2597 MGMT-18050: UI warning icon not changed to error icon on 24 hours timeout in hosts table - 2.32
  libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
Labels: lgtm, size/S, OCM, jira/valid-reference

#2598 MGMT-16996: Show only LVMS requirements messages from BE
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmHostRequirements.tsx
Labels: lgtm, size/XS, jira/valid-reference

#2600 MGMT-16996: Show only LVMS requirements messages from BE - 2.32
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmHostRequirements.tsx
Labels: lgtm, size/XS, OCM, jira/valid-reference

#2599 MGMT-17123: Add CPU and RAM requirements for MCE operator
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceRequirements.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: lgtm, size/M, jira/valid-reference

#2601 MGMT-17123: Add CPU and RAM requirements for MCE operator - 2.32
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceRequirements.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: lgtm, size/M, OCM, jira/valid-reference

#2605 MGMT-17118: Host agent name change, UX flow could be improved
  libs/ui-lib/lib/cim/components/modals/EditAgentModal.tsx
Labels: lgtm, size/XS, jira/valid-reference

#2604 MGMT-17291: Enable French and Spanish in CIM
  libs/locales/@types/es.d.ts
  libs/locales/@types/fr.d.ts
  libs/locales/lib/es/translation.json
  libs/locales/lib/fr/translation.json
  libs/locales/lib/ja/translation.json
  libs/locales/lib/ko/translation.json
  libs/locales/lib/zh/translation.json
  libs/locales/package.json
Labels: lgtm, size/XXL, jira/valid-reference

#2603 MGMT-17291: Enable French and Spanish in CIM [BACKPORT 2.11]
  libs/locales/@types/es.d.ts
  libs/locales/@types/fr.d.ts
  libs/locales/lib/es/translation.json
  libs/locales/lib/fr/translation.json
  libs/locales/lib/ja/translation.json
  libs/locales/lib/ko/translation.json
  libs/locales/lib/zh/translation.json
  libs/locales/package.json
Labels: lgtm, size/XXL, jira/valid-reference

#2616 MGMT-18211: Static IP dualstack form - UI sends incorrect NMstate to BE
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/dummyData.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataToInfraEnvField.ts
Labels: lgtm, size/M, OCM, jira/valid-reference

#2618 MGMT-18211: Static IP dualstack form - UI sends incorrect NMstate to BE - 2.32
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/dummyData.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataToInfraEnvField.ts
Labels: lgtm, size/M, OCM, jira/valid-reference

#2617 MGMT-18241: Review docs_links file to align all the URLs with correct links
  libs/ui-lib/lib/common/config/docs_links.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
Labels: lgtm, size/M, jira/valid-reference

#2622 MGMT-18241: Review docs_links file to align all the URLs with correct links - 2.32
  libs/ui-lib/lib/common/config/docs_links.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/constants.tsx
Labels: lgtm, size/M, OCM, jira/valid-reference
