Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2024-12, with the labels that each got.

#2720 MGMT-18389: Solving problems with nmstate with VLAN+bonds
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataToInfraEnvField.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/nmstateYaml.ts
Labels: size/M, jira/valid-reference

#2722 MGMT-19389: nmstate not generated well with bonds - 2.36
  libs/ui-lib-tests/cypress/integration/static-ip/2-configure-static-ip-host-specific.cy.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataFromInfraEnvField.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataToInfraEnvField.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/nmstateYaml.ts
Labels: size/M, jira/valid-reference

#2723 MGMT-19409: Disable OpenShift AI when LVM is enabled
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenShiftAICheckbox.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
Labels: lgtm, size/S, jira/valid-reference

#2725 MGMT-19445: MAC address should be empty
  libs/ui-lib-tests/cypress/integration/static-ip/2-configure-static-ip-host-specific.cy.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataFromInfraEnvField.ts
Labels: size/XS, jira/valid-reference

#2728 MGMT-19445: MAC address should be empty - 2.36
  libs/ui-lib-tests/cypress/integration/static-ip/2-configure-static-ip-host-specific.cy.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataFromInfraEnvField.ts
Labels: size/XS, jira/valid-reference

#2731 MGMT-19497: Not add VLAN configuration to bonds - 2.36
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/nmstateYaml.ts
Labels: size/XS, jira/valid-reference

#2733 NO-ISSUE: Change order in Operator's page
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/XS, OCM

#2734 NO-ISSUE: Change order in Operator's page - 2.36
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/XS, OCM, jira/valid-reference

#2717 MGMT-19298: Disable CNV operator when user selects MTV operator
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
Labels: size/S, jira/valid-reference

#2724 MGMT-19300: Enable 4/5 CP installation in day1 using assisted-installer
  libs/types/assisted-installer-service.d.ts
  libs/ui-lib-tests/cypress/fixtures/infra-envs/feature-support.ts
  libs/ui-lib-tests/cypress/fixtures/infra-envs/openshift-versions.ts
  libs/ui-lib-tests/cypress/integration/create-sno/0-create-cluster.cy.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/validations-new-cluster-page.cy.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
  libs/ui-lib-tests/cypress/support/variables/cluster-details.ts
  libs/ui-lib-tests/cypress/views/clusterDetails.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetails/ClusterDetailsForm.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetails/Fields/ControlPlaneNodesField.ts
  libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts
  libs/ui-lib/lib/common/components/clusterWizard/types.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmSNOControlGroup.tsx
  libs/ui-lib/lib/ocm/services/ClusterDetailsService.ts
Labels: size/L, jira/valid-reference

#2719 MGMT-19235: Add OpenShift sandboxed containers operator
  libs/locales/lib/en/translation.json
  libs/types/assisted-installer-service.d.ts
  libs/ui-lib-tests/cypress/fixtures/cluster/validation-info-host-discovery.ts
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/common/config/docs_links.ts
  libs/ui-lib/lib/common/types/clusters.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OscCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/Operators.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/_wizardTransition.test.ts
  libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
  libs/ui-lib/lib/ocm/services/OperatorsService.tsx
Labels: lgtm, size/L, jira/valid-reference

#2736 MGMT-19167: Add MTU validation
  libs/locales/lib/en/translation.json
  libs/types/assisted-installer-service.d.ts
  libs/ui-lib-tests/cypress/fixtures/cluster/validation-info-host-discovery.ts
  libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
  libs/ui-lib/lib/common/components/hosts/HostValidationGroups.tsx
  libs/ui-lib/lib/common/components/hosts/utils.ts
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/common/config/docs_links.ts
  libs/ui-lib/lib/ocm/components/clusterWizard/_wizardTransition.test.ts
  libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts
Labels: size/L, OCM, jira/valid-reference

#2737 NO-ISSUE: Remove console.log from code
  libs/ui-lib/lib/common/components/hosts/HostStatus.tsx
  libs/ui-lib/lib/common/components/hosts/HostValidationGroups.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/formDataToInfraEnvField.ts
Labels: size/S, jira/valid-reference

#2738 Bump @sentry/browser from 6.19.7 to 7.119.1
  apps/assisted-ui/package.json
  libs/ui-lib/lib/ocm/components/SentryErrorMonitorContextProvider.tsx
  libs/ui-lib/lib/ocm/sentry.ts
  yarn.lock
Labels: size/L
