Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2024-10, with the labels that each got.

#2671 ACM-14148: "Invalid value for key _targetInst" error when trying to search for host
  libs/ui-lib/lib/cim/components/InfraEnv/InfraTableToolbar.tsx
  libs/ui-lib/lib/common/components/hosts/utils.ts
Labels: lgtm, size/XS, jira/valid-reference

#2670 ACM-14148: "Invalid value for key _targetInst" error when trying to search for host
  libs/ui-lib/lib/cim/components/InfraEnv/InfraTableToolbar.tsx
  libs/ui-lib/lib/common/components/hosts/utils.ts
Labels: size/XS, jira/valid-reference

#2665 MGMT-18847: UI does not recognize externally provisioned BMH status
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/helpers/agentStatus.tsx
Labels: lgtm, size/XS, jira/valid-reference

#2664 MGMT-18847: UI does not recognize externally provisioned BMH status
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/helpers/agentStatus.tsx
Labels: size/XS, jira/valid-reference

#2663 MGMT-18847: UI does not recognize externally provisioned BMH status
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/helpers/agentStatus.tsx
Labels: lgtm, size/XS, jira/valid-reference

#2679 MGMT-19043: Migrate deprecated Table component used in Assisted Installer UI to the PF5 Table component
  libs/ui-lib-tests/cypress/views/bareMetalDiscovery.ts
  libs/ui-lib-tests/cypress/views/hostsTableSection.ts
  libs/ui-lib-tests/cypress/views/modals/EventsModal.ts
  libs/ui-lib-tests/cypress/views/networkingPage.ts
  libs/ui-lib-tests/cypress/views/storagePage.ts
  libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
  libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/NodePoolsTable.tsx
  libs/ui-lib/lib/cim/components/modals/MassApproveAgentModal.tsx
  libs/ui-lib/lib/cim/components/modals/MassDeleteAgentModal.tsx
  libs/ui-lib/lib/common/components/clusterWizard/ReviewHostsInventory.tsx
  libs/ui-lib/lib/common/components/hosts/AITable.tsx
  libs/ui-lib/lib/common/components/hosts/AITableMemo.tsx
  libs/ui-lib/lib/common/components/hosts/HostRowDetail.tsx
  libs/ui-lib/lib/common/components/hosts/tableUtils.tsx
  libs/ui-lib/lib/common/components/storage/DisksTable.tsx
  libs/ui-lib/lib/common/components/storage/StorageUtils.tsx
  libs/ui-lib/lib/common/components/ui/EventsList.tsx
  libs/ui-lib/lib/common/components/ui/table/index.ts
  libs/ui-lib/lib/common/components/ui/table/utils.ts
  libs/ui-lib/lib/common/components/ui/table/wrappable.css
  libs/ui-lib/lib/common/components/ui/table/wrappable.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationTableBase.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewClusterDetailTable.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewCustomManifestsTable.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewNetworkingTable.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewOperatorsTable.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewPlatformTable.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClustersTable.tsx
  libs/ui-lib/lib/ocm/components/hosts/HardwareStatus.tsx
Labels: lgtm, size/XXL, jira/valid-reference

#2680 MGMT-18925: Add Hosts from Cisco Intersight
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/common/components/clusterConfiguration/DownloadIso.tsx
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: size/S, jira/valid-reference

#2682 MGMT-18652: Add data-testid selector to breadcrumbs
  libs/ui-lib/lib/ocm/components/clusters/ClusterBreadcrumbs.tsx
Labels: size/S, jira/valid-reference

#2684 MGMT-19132: Broken url in networking page
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: size/S, jira/valid-reference
