Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2025-09, with the labels that each got.

#3149 Do not push to quay the chatbot releases
  .github/workflows/push-to-master.yaml
Labels: lgtm, approved, size/XS

#3154 [releases/v2.15-cim] MGMT-21261: keep link to pull secret visible
  libs/ui-lib-tests/cypress/views/clusterDetails.ts
  libs/ui-lib/lib/common/components/ui/formik/TextAreaField.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#3160 Add MessageEntry component for unified chatbot
  libs/chatbot/lib/components/ChatBot/MessageEntry.tsx
  libs/chatbot/lib/components/ChatBot/helpers.ts
  libs/chatbot/lib/index.ts
  libs/chatbot/package.json
  yarn.lock
Labels: lgtm, approved, size/L

#3163 NO-ISSUE: Avoid showing 0, when there are no actions
  libs/chatbot/lib/components/ChatBot/MessageEntry.tsx
Labels: lgtm, approved, size/M, jira/valid-reference
