Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2025-10, with the labels that each got.

#3182 MGMT-21888: Change NMstate operator docs link
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: lgtm, approved, size/S, jira/severity-moderate, jira/valid-reference

#3188 OCPBUGS-62680: Include assisted disconnected UI image in release payload
  apps/assisted-disconnected-ui/Containerfile.ocp
Labels: lgtm, approved, size/XS, jira/valid-bug, jira/valid-reference

#3191 Fixing errors when creating cluster from Assisted Migration
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx
Labels: lgtm, approved, size/S

#3177 ACM-24159: Ability to set up the Hosted Control Plane cluster without worker nodes from ACM UI
  libs/ui-lib/lib/cim/components/Hypershift/modals/ManageHostsModal.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference
