Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2025-06, with the labels that each got.

#2952 MGMT-19883: Add options to install Two Node Openshift with Arbiter(TNA) with Assisted Installer UI
  libs/locales/lib/en/translation.json
  libs/types/assisted-installer-service.d.ts
  libs/ui-lib-tests/cypress/views/clusterDetails.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionControlGroup.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/DiskEncryptionFields/DiskEncryptionValues.ts
  libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts
  libs/ui-lib/lib/common/components/clusterWizard/types.ts
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmTNADisclaimer.tsx
  libs/ui-lib/lib/ocm/services/DiskEncryptionService.ts
Labels: lgtm, approved, size/L, jira/valid-reference

#2978 MGMT-20762: Show all available versions is ignoring basic version format v2.12
  libs/ui-lib/lib/cim/components/helpers/versions.ts
Labels: lgtm, approved, size/XS, jira/valid-reference

#2979 MGMT-20770: Show all available versions is ignoring basic version format v2.11
  libs/ui-lib/lib/cim/components/helpers/versions.ts
Labels: lgtm, approved, size/XS, jira/valid-reference

#2987 ECOPROJECT-2933: Disable virtualization bundle when cluster come from Migration Assessment
  libs/ui-lib/lib/common/types/ui-settings.ts
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsBundle.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#2984 MGMT-20258: The link to OpenShift networking documentation opens to 404 error
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: lgtm, approved, size/S, jira/valid-reference

#2982 MGMT-20809: Add hosts menu is not fully seen on infraenv page
  libs/ui-lib/lib/cim/components/InfraEnv/AddHostDropdown.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#2994 MGMT-20611: Make KMM operator URL dynamic
  libs/ui-lib/lib/common/components/operators/operatorSpecs.tsx
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: lgtm, approved, size/S, jira/valid-reference

#2995 MGMT-20840 fix ocp version comparison
  libs/ui-lib/lib/cim/components/helpers/versions.ts
  libs/ui-lib/lib/common/components/operators/operatorSpecs.tsx
  libs/ui-lib/lib/common/config/docs_links.ts
  libs/ui-lib/lib/common/utils.ts
Labels: lgtm, approved, size/L

#2996 MGMT-20576: Make hosts list scrollable inside Events table
  libs/ui-lib/lib/common/components/ui/ClusterEventsToolbar.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#2999 MGMT-20872: Change min OCP version in TNA disabled reason
  libs/ui-lib/lib/ocm/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#2998 MGMT-20483: Use categories for operators
  libs/ui-lib/lib/common/components/clusterDetail/OperatorsProgressItem.tsx
  libs/ui-lib/lib/common/components/newFeatureSupportLevels/types.ts
  libs/ui-lib/lib/common/components/operators/operatorDescriptions.tsx
  libs/ui-lib/lib/common/components/operators/operatorSpecs.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmOperatorProgressItem.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OperatorCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewOperatorsTable.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/ProgressBarAlerts.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsBundle.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsSelect.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
Labels: lgtm, approved, size/XL, jira/valid-reference

#3005 MGMT-20896: Add id to folder dropdown in custom manifests page
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/FolderDropdown.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#3001 MGMT-20871: Reset ControlPlaneNodesDropdown when Openshift Version changes
  libs/ui-lib/lib/ocm/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
Labels: lgtm, approved, size/M, jira/valid-reference

#3009 MGMT-20902: Add TechPreview badge for TNA in OCP 4.19
  libs/ui-lib/lib/ocm/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
Labels: lgtm, approved, size/M, jira/valid-reference

#3014 MGMT-20893: Remove Remediation operators
  libs/ui-lib/lib/common/components/operators/operatorSpecs.tsx
  libs/ui-lib/lib/ocm/services/OperatorsService.tsx
Labels: lgtm, approved, size/M, jira/valid-reference

#3013 MGMT-20931: Always show the box-shadow in the floating Dropdown menus
  libs/ui-lib/lib/common/components/hosts/DiskRole.tsx
  libs/ui-lib/lib/common/components/ui/SimpleDropdown.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#3015 MGMT-20895: Use humanized label for displaying the selected subnet
  libs/ui-lib-tests/cypress/integration/dualstack/2-networking.cy.ts
  libs/ui-lib-tests/cypress/views/networkingPage.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/SubnetsDropdown.tsx
Labels: lgtm, approved, size/M, jira/valid-reference

#3018 MGMT-20483: Adding new categories for operators
  libs/ui-lib/lib/common/components/operators/operatorSpecs.tsx
Labels: lgtm, approved, size/L, jira/valid-reference

#3021 OCPBUGS-58156: Remove operators from OVE UI
  libs/ui-lib/lib/common/config/constants.ts
Labels: lgtm, approved, size/XS, jira/valid-bug, jira/valid-reference

#3024 [releases/v2.14-cim] MGMT-20898: In disconnected Standalone cluster installation ClusterImageSet is not getting populated in AgentClusterInstall
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx
Labels: lgtm, approved, size/M, jira/valid-reference

#3017 MGMT-20842: Add search to operators page
  libs/ui-lib/lib/common/components/operators/operatorSpecs.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OperatorCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsBundle.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsSelect.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: lgtm, approved, size/L, jira/valid-reference
