Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2025-07, with the labels that each got.

#3028 MGMT-20976: Disable table actions when no hosts have been selected
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/common/components/hosts/TableToolbar.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#3029 MGMT-20939: Refresh cluster-level validations on host role update
  libs/ui-lib/lib/ocm/components/hosts/use-hosts-table.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#3031 MGMT-20742: Shorten operators debounce for responsiveness
  libs/ui-lib/lib/ocm/components/clusterWizard/Operators.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#3032 OpenShift docs for 4.19 are already available
  libs/ui-lib/lib/common/components/operators/operatorSpecs.tsx
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: lgtm, approved, size/M

#3016 MGMT-20953: Add AI ChatBot
  .containerignore
  docs/DEVELOPMENT.md
  libs/chatbot/.eslintrc.cjs
  libs/chatbot/lib/assets/avatarimg.svg
  libs/chatbot/lib/assets/rh-logo.svg
  libs/chatbot/lib/components/ChatBot/ChatBot.tsx
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
  libs/chatbot/lib/components/ChatBot/Chatbot.css
  libs/chatbot/lib/index.ts
  libs/chatbot/lib/typings.d.ts
  libs/chatbot/package.json
  libs/chatbot/tsconfig.eslint.json
  libs/chatbot/tsconfig.json
  libs/ui-lib/lib/ocm/components/Routes.tsx
  package.json
  yarn.lock
Labels: lgtm, approved, size/XXL, jira/valid-reference

#3037 MGMT-20399: Allow to add in day2 hosts with other CPU architectures in s390x clusters
  libs/ui-lib/lib/common/types/cpuArchitecture.ts
Labels: lgtm, approved, size/S, jira/valid-reference

#3040 Make chatbot public
  libs/chatbot/package.json
Labels: lgtm, approved, size/XS

#3045 MGMT-21111: Refresh clusters automatically every minute
  libs/ui-lib/lib/common/components/fetching/EventListFetch.tsx
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
  libs/ui-lib/lib/ocm/components/clusters/Clusters.tsx
  libs/ui-lib/lib/ocm/components/clusters/clusterPolling.ts
Labels: lgtm, approved, size/S, jira/valid-reference

#3051 MGMT-21122: Add feedback form to the Chatbot responses
  libs/chatbot/lib/components/ChatBot/BotMessage.tsx
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
Labels: lgtm, approved, size/L, jira/valid-reference

#3055 MGMT-20897: Add new Openshift AI - no GPU validation
  libs/types/assisted-installer-service.d.ts
  libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts
Labels: lgtm, approved, size/S, jira/valid-reference

#3062 Revert "OCPBUGS-58156: Remove operators from OVE UI"
  libs/ui-lib/lib/common/config/constants.ts
Labels: lgtm, approved, size/XS, jira/invalid-bug, jira/valid-reference

#3059 MGMT-21223 change buttons behaviour
  libs/chatbot/lib/components/ChatBot/ChatBot.tsx
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
  libs/chatbot/lib/components/ChatBot/ConfirmNewChatModal.tsx
Labels: lgtm, approved, size/M

#3035 MGMT-20999: Fix background color in readonly form controls in PF5
  libs/ui-lib/lib/cim/global.css
  libs/ui-lib/lib/cim/index.ts
Labels: lgtm, approved, size/S, jira/valid-reference

#3075 [releases/v2.15-cim] MGMT-21014: Impossible to choose n+1 or n-4 version - only n, n+1 and n+2 are shown in OCP version dropdown
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/DetailsStep/DetailsForm.tsx
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/DetailsStep/DetailsStep.tsx
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/DetailsStep/types.ts
  libs/ui-lib/lib/cim/components/Hypershift/hooks/useSupportedOCPVersions.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/index.ts
Labels: lgtm, approved, size/L, jira/valid-reference

#3077 [releases/v2.12-cim] MGMT-21014: Impossible to choose n+1 or n-4 version - only n, n+1 and n+2 are shown in OCP version dropdown
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/DetailsStep/DetailsForm.tsx
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/DetailsStep/DetailsStep.tsx
  libs/ui-lib/lib/cim/components/Hypershift/HostedClusterWizard/DetailsStep/types.ts
  libs/ui-lib/lib/cim/components/Hypershift/hooks/useSupportedOCPVersions.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/OpenShiftVersionSelect.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/index.ts
Labels: lgtm, approved, size/L, jira/valid-reference

#3073 MGMT-21259: Do not animate scroll when chat is reopened
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#3074 MGMT-21260 focus input on new chat
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
  libs/chatbot/lib/components/ChatBot/helpers.ts
Labels: lgtm, approved, size/M

#3060 MGMT-19730: Search in host inventory does not work as expected
  libs/ui-lib/lib/cim/components/Agent/tableUtils.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvAgentTable.tsx
  libs/ui-lib/lib/common/components/hosts/AITable.tsx
  libs/ui-lib/lib/common/components/hosts/HostsTable.tsx
  libs/ui-lib/lib/common/components/hosts/utils.ts
Labels: lgtm, approved, size/L, jira/valid-reference
