Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2025-05, with the labels that each got.

#2946 NO-ISSUE: Change 'CPUs' to 'CPU cores'
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/ClusterDeployment/ShortCapacitySummary.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OperatorCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/bundleSpecs.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#2947 Update list of ABI operators
  libs/ui-lib/lib/common/config/constants.ts
Labels: lgtm, approved, size/S

#2948 MGMT-20507: Static IP configure via should appear only in the first page
  libs/ui-lib-tests/cypress/integration/static-ip/2-configure-static-ip-host-specific.cy.ts
  libs/ui-lib-tests/cypress/integration/static-ip/3-configure-static-ip-yaml.cy.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/StaticIpPage.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#2950 MGMT-20616: Refactor Header component to use not deprecated components of patternfly
  apps/assisted-ui/src/components/Header.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#2949 MGMT-20337: Problems with Add hosts tab that appears before cluster is installed
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/utils.ts
Labels: lgtm, approved, size/XS, jira/valid-reference

#2953 MGMT-20659: Select virtualization bundle and LVM operator when user came from Assisted Migration wizard
  libs/ui-lib/lib/ocm/components/clusterConfiguration/CustomManifestCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx
  libs/ui-lib/lib/ocm/config/constants.ts
  libs/ui-lib/lib/ocm/services/ClustersService.ts
Labels: lgtm, approved, size/L, jira/valid-reference

#2960 MGMT-20699: Change data-testid for disk row adding host id
  libs/ui-lib-tests/cypress/integration/storage/storage-step.cy.ts
  libs/ui-lib-tests/cypress/views/hostsTableSection.ts
  libs/ui-lib-tests/cypress/views/storagePage.ts
  libs/ui-lib/lib/common/components/storage/DisksTable.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#2941 MGMT-20404: Refactor dropdown component import package
  libs/ui-lib-tests/cypress/fixtures/infra-envs/openshift-versions.ts
  libs/ui-lib-tests/cypress/integration/create-sno/0-create-cluster.cy.ts
  libs/ui-lib-tests/cypress/integration/day-2/2-adding-hosts.cy.ts
  libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-creation.cy.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
  libs/ui-lib-tests/cypress/views/bareMetalDiscovery.ts
  libs/ui-lib-tests/cypress/views/bareMetalDiscoveryIsoModal.ts
  libs/ui-lib-tests/cypress/views/clusterDetails.ts
  libs/ui-lib-tests/cypress/views/common.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetails/Fields/ControlPlaneNodesField.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetails/Fields/CpuArchitectureField.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetails/Fields/ExternalPartnerIntegrationsField.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetails/Fields/OpenShiftVersionField.ts
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/LabelsSelector.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/AddHostDropdown.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvAgentTable.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvOpenShiftVersionDropdown.tsx
  libs/ui-lib/lib/cim/components/common/CpuArchitectureDropdown.tsx
  libs/ui-lib/lib/cim/components/modals/MassApproveAction.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
  libs/ui-lib/lib/common/components/hosts/DiskRole.tsx
  libs/ui-lib/lib/common/components/hosts/HostToolbarActions.tsx
  libs/ui-lib/lib/common/components/hosts/TableToolbar.tsx
  libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.css
  libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx
  libs/ui-lib/lib/common/components/ui/SimpleDropdown.tsx
  libs/ui-lib/lib/common/index.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/CpuArchitectureDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageTypeDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmBaseDomainField.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/manifestsConfiguration/components/FolderDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/SubnetsDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/platformIntegration/ExternalPlatformDropdown.tsx
Labels: lgtm, approved, size/XXL, jira/valid-reference

#2964 MGMT-20508: Not correct number of CPs on cluster details page when trying to cont…
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference
