Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2025-08, with the labels that each got.

#3084 MGMT-21333: Enable chatbot in standalone UI
  apps/assisted-ui/Containerfile
  apps/assisted-ui/README.md
  apps/assisted-ui/deploy/nginx.conf
  apps/assisted-ui/deploy/start.sh
  apps/assisted-ui/env.template.js
  apps/assisted-ui/index.html
  apps/assisted-ui/package.json
  apps/assisted-ui/public/env.js
  apps/assisted-ui/src/components/App.tsx
  apps/assisted-ui/src/components/Chatbot.tsx
  apps/assisted-ui/src/config.ts
  apps/assisted-ui/src/main.tsx
  apps/assisted-ui/vite.config.ts
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
  libs/chatbot/package.json
  yarn.lock
Labels: lgtm, approved, size/L, jira/valid-reference

#3087 Define default URL for chatbot API
  apps/assisted-ui/deploy/start.sh
Labels: lgtm, approved, size/XS

#3090 [releases/v0.0-chatbot] MGMT-21350: Fix SSE parsing and set break-word for all chatbot messag…
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
  libs/chatbot/lib/components/ChatBot/Chatbot.css
  libs/chatbot/tsconfig.json
Labels: lgtm, approved, size/M, jira/valid-reference

#3094 use refresh token to obtain fresh access token
  apps/assisted-ui/README.md
  apps/assisted-ui/deploy/nginx.conf
  apps/assisted-ui/deploy/start.sh
  apps/assisted-ui/env.template.js
  apps/assisted-ui/public/env.js
  apps/assisted-ui/src/components/App.tsx
  apps/assisted-ui/src/components/Chatbot.tsx
  apps/assisted-ui/src/main.tsx
  apps/assisted-ui/vite.config.ts
Labels: lgtm, approved, size/M

#3089 Add data-testid to refresh icon in clusters list page
  libs/ui-lib/lib/ocm/components/clusters/ClustersListToolbar.tsx
Labels: lgtm, approved, size/XS

#3096 MGMT-20575: Add data-testid to items in the cluster events filter
  libs/ui-lib/lib/common/components/ui/ClusterEventsToolbar.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#3098 MGMT-21351: Do not allow sending empty msgs
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#3100 Bump PF chatbot, update loading msgs and improve error handling
  apps/assisted-ui/package.json
  apps/assisted-ui/src/components/Chatbot.tsx
  libs/chatbot/lib/components/ChatBot/BotMessage.tsx
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
  libs/chatbot/package.json
  yarn.lock
Labels: lgtm, approved, size/L

#3102 MGMT-21339: Add chatbot actions
  libs/chatbot/lib/components/ChatBot/BotMessage.tsx
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
  libs/chatbot/lib/components/ChatBot/helpers.ts
  libs/chatbot/lib/components/ChatBot/types.ts
  libs/chatbot/package.json
  yarn.lock
Labels: lgtm, approved, size/L, jira/valid-reference

#3103 Include cookies in chatbot requests
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
Labels: lgtm, approved, size/XS

#3101 MGMT-21373: Add the new virtualization operators to the UI
  libs/locales/lib/en/translation.json
  libs/types/assisted-installer-service.d.ts
  libs/ui-lib/lib/common/components/operators/operatorDescriptions.tsx
  libs/ui-lib/lib/common/components/operators/operatorSpecs.tsx
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: lgtm, approved, needs-ok-to-test, size/L, jira/valid-reference

#3110 MGMT-21375: Show link to cluster details on cluster install action
  apps/assisted-ui/src/components/Chatbot.tsx
  libs/chatbot/lib/components/ChatBot/BotMessage.tsx
  libs/chatbot/lib/components/ChatBot/ChatBot.tsx
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
  libs/chatbot/lib/components/ChatBot/helpers.ts
  libs/chatbot/lib/hooks/use-message.ts
Labels: lgtm, approved, size/M, jira/valid-reference

#3114 Add href to download iso button
  libs/chatbot/lib/components/ChatBot/BotMessage.tsx
Labels: lgtm, approved, size/XS

#3129 MGMT-21584: Disable disconnected switch in cluster edit
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/disconnected/BasicStep.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/disconnected/InstallDisconnectedSwitch.tsx
Labels: lgtm, approved, size/M, jira/valid-reference

#3136 Validate create_cluster response to be a valid UUID
  libs/chatbot/lib/components/ChatBot/helpers.ts
  libs/chatbot/package.json
  yarn.lock
Labels: lgtm, approved, size/XS

#3141 Bump PF6 chatbot and disable markdown
  apps/assisted-ui/package.json
  apps/assisted-ui/src/components/Chatbot.tsx
  libs/chatbot/lib/components/ChatBot/BotMessage.tsx
  libs/chatbot/lib/components/ChatBot/ChatBot.tsx
  libs/chatbot/lib/components/ChatBot/ChatBotHistory.tsx
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
  libs/chatbot/lib/components/ChatBot/helpers.ts
  libs/chatbot/package.json
  package.json
  yarn.lock
Labels: lgtm, approved, size/L

#3143 Remove operators from ABI that are not yet included
  libs/ui-lib/lib/common/config/constants.ts
Labels: lgtm, approved, size/XS

#3147 Create external link component and reuse it
  libs/chatbot/lib/components/ChatBot/AIAlert.tsx
  libs/chatbot/lib/components/ChatBot/BotMessage.tsx
  libs/chatbot/lib/components/ChatBot/ChatBot.tsx
  libs/chatbot/lib/components/ChatBot/ChatBotButton.tsx
  libs/chatbot/lib/components/ChatBot/ChatBotWindow.tsx
  libs/chatbot/lib/components/ChatBot/Chatbot.css
  libs/chatbot/lib/components/ChatBot/DevPreviewBadge.tsx
  libs/chatbot/lib/components/ChatBot/ExternalLink.tsx
  libs/chatbot/lib/components/ChatBot/PreviewBadge.tsx
Labels: lgtm, approved, size/L
