Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2025-02, with the labels that each got.

#2778 MGMT-19467: Operators step redesign
  libs/locales/lib/en/translation.json
  libs/types/assisted-installer-service.d.ts
  libs/ui-lib-tests/cypress/fixtures/cluster/base-cluster.ts
  libs/ui-lib-tests/cypress/fixtures/create-mn/index.ts
  libs/ui-lib-tests/cypress/fixtures/read-only/5-cluster-ready.ts
  libs/ui-lib-tests/cypress/fixtures/read-only/index.ts
  libs/ui-lib-tests/cypress/integration/features/read-only-multi-node.cy.ts
  libs/ui-lib-tests/cypress/support/interceptors.ts
  libs/ui-lib/lib/common/api/assisted-service/BundleAPI.ts
  libs/ui-lib/lib/common/api/assisted-service/OperatorsAPI.ts
  libs/ui-lib/lib/common/components/clusterWizard/types.ts
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/common/selectors/clusterSelectors.ts
  libs/ui-lib/lib/common/types/clusters.ts
  libs/ui-lib/lib/common/types/ui-settings.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AuthorinoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateRequirements.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenShiftAICheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/PipelinesChekbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServerlessCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/SupportedOperators.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/Operators.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
  libs/ui-lib/lib/ocm/services/BundleService.ts
  libs/ui-lib/lib/ocm/services/OperatorsService.tsx
Labels: size/XXL, jira/valid-reference

#2780 Improvement in the new Operators page behavior
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AuthorinoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/PipelinesChekbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServerlessCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/SupportedOperators.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
Labels: size/L

#2784 MGMT-19441: Disable Openshift AI (NVIDIA) bundle for SNO clusters
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/S, jira/valid-reference

#2785 MGMT-19938: Get disabled reason for all the operators when the operators page is loaded
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AuthorinoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenShiftAICheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OscCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/PipelinesChekbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServerlessCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/SupportedOperators.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/L, jira/valid-reference

#2786 MGMT-19981: Disable Node Feature Discovery operator with the support levels endpoint
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/SupportedOperators.tsx
Labels: size/XS, jira/valid-reference

#2772 MGMT-19808: Host's details table disks is not showing well
  libs/ui-lib/lib/common/components/storage/DisksTable.tsx
Labels: size/M, jira/valid-reference

#2777 MGMT-19784: 'compatible-agent' is a soft validation
  libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts
Labels: size/XS, jira/valid-reference

#2795 NO-ISSUE: Change actions/upload-artifact@v3 to actions/upload-artifact@v4 in GH actions
  .github/workflows/pull-request.yaml
Labels: lgtm, size/XS, jira/valid-reference

#2782 NO-ISSUE: "Worker" translation string missing count
  libs/ui-lib/lib/common/config/constants.ts
Labels: size/XS, jira/valid-reference

#2788 MGMT-19589: Renaming is available in drop-down for a host in removing from cluster state, no warning/error that it's impossible in opened pop-up
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/common/components/hosts/EditHostForm.tsx
Labels: size/S, jira/valid-reference

#2776 ACM-17263: Add a host using BMC form should have a validation for BMC address
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
  libs/ui-lib/package.json
  yarn.lock
Labels: size/M, jira/valid-reference

#2769 MGMT-19364: Implement UI for external platform
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/ExternalPlatformsDropdown.tsx
Labels: size/M, jira/valid-reference

#2773 MGMT-19593: When choose User-Managed-Networking and going back to default Cluster-managed Networking - error preventing the following flow
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/NetworkConfiguration.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/networkConfigurationValidation.ts
  libs/ui-lib/lib/cim/components/ClusterDeployment/use-networking-formik.ts
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
  libs/ui-lib/lib/common/components/clusterWizard/networkingSteps/AvailableSubnetsControl.tsx
  libs/ui-lib/lib/common/components/clusterWizard/networkingSteps/VirtualIPControlGroup.tsx
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
Labels: size/L, jira/valid-reference

#2793 MGMT-19593: When choose User-Managed-Networking and going back to default Cluster-managed Networking - error preventing the following flow
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/NetworkConfiguration.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/networkConfigurationValidation.ts
  libs/ui-lib/lib/cim/components/ClusterDeployment/use-networking-formik.ts
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
  libs/ui-lib/lib/common/components/clusterWizard/networkingSteps/AvailableSubnetsControl.tsx
  libs/ui-lib/lib/common/components/clusterWizard/networkingSteps/VirtualIPControlGroup.tsx
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
Labels: lgtm, size/L, jira/valid-reference

#2792 MGMT-19364: Implement UI for external platform
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/ExternalPlatformsDropdown.tsx
Labels: size/M, jira/valid-reference

#2787 MGMT-19778: Steps of configuring of Standalone cluster are not progressing
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/ClusterDeployment/ACMClusterDeploymentDetailsStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentCreateProgress.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentReviewStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizardContext.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizardFooter.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizardNavigation.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizardStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/components/ClusterDeploymentHostsSelectionAdvanced.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/components/ClusterScaleUpAutoHostsSelection.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/components/ValidationSection.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/constants.ts
  libs/ui-lib/lib/cim/components/ClusterDeployment/index.ts
  libs/ui-lib/lib/cim/components/ClusterDeployment/types.ts
Labels: lgtm, size/XXL, jira/valid-reference

#2798 MGMT-19589: Renaming is available in drop-down for a host in removing from cluster state, no warning/error that it's impossible in opened pop-up
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/common/components/hosts/EditHostForm.tsx
Labels: size/S, jira/valid-reference

#2799 MGMT-19591: Update BMH hostname annotation instead of Agent's spec
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostDiscoveryTable.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscovery.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/types.ts
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvAgentTable.tsx
  libs/ui-lib/lib/cim/components/helpers/agents.ts
  libs/ui-lib/lib/cim/components/modals/EditAgentModal.tsx
  libs/ui-lib/lib/cim/components/modals/ScaleUpModal.tsx
  libs/ui-lib/lib/common/components/hosts/EditHostForm.tsx
Labels: size/L, jira/valid-reference

#2794 ACM-17263: Add a host using BMC form should have a validation for BMC address
  libs/ui-lib/lib/common/components/ui/formik/validationSchemas.ts
  libs/ui-lib/package.json
  yarn.lock
Labels: size/M, jira/valid-reference

#2800 MGMT-19853: Add dev-preview doc link
  libs/ui-lib/lib/common/components/ui/DeveloperPreview.tsx
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: size/XS, jira/valid-reference

#2802 Add OWNERS file
  OWNERS
  apps/assisted-disconnected-ui/proxy/config/config.go
Labels: lgtm, size/S

#2804 Revert "add OCP custom version button to the top of the dropbox"
  libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-creation.cy.ts
  libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx
Labels: lgtm, approved, size/M

#2791 ACM-17500: Adding customkubeconfig to HostedClusterK8sResource type
  libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/HypershiftKubeconfigDownload.tsx
  libs/ui-lib/lib/cim/components/Hypershift/types.ts
Labels: lgtm, approved, size/S, jira/valid-reference

#2797 MGMT-19778: Steps of configuring of Standalone cluster are not progressing
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/ClusterDeployment/ACMClusterDeploymentDetailsStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentCreateProgress.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostSelectionStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentHostsDiscoveryStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentNetworkingStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentReviewStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizard.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizardContext.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizardFooter.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizardNavigation.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentWizardStep.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/components/ClusterDeploymentHostsSelectionAdvanced.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/components/ClusterScaleUpAutoHostsSelection.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/components/ValidationSection.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/constants.ts
  libs/ui-lib/lib/cim/components/ClusterDeployment/index.ts
  libs/ui-lib/lib/cim/components/ClusterDeployment/types.ts
Labels: lgtm, size/XXL, jira/valid-reference

#2805 Operators redesign followup
  libs/ui-lib/lib/common/config/docs_links.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AuthorinoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/PipelinesChekbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServerlessCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/L

#2806 Operators redesign followup - 2
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
Labels: size/L

#2807 Operators redesign followup - 2.38
  libs/ui-lib/lib/common/config/docs_links.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AuthorinoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/PipelinesChekbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServerlessCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/L

#2809 ACM-17500: Adding customkubeconfig to HostedClusterK8sResource type
  libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/HypershiftKubeconfigDownload.tsx
  libs/ui-lib/lib/cim/components/Hypershift/types.ts
Labels: lgtm, size/S, jira/valid-reference

#2811 MGMT-20044: Adding requirements and operators in bundle popover content - 2.38
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenShiftAIRequirements.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenshiftAINvidiaRequirements.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/VirtualizationRequirements.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/M, jira/valid-reference

#2812 Revert "MGMT-19364: Implement UI for external platform"
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/ExternalPlatformsDropdown.tsx
Labels: lgtm, size/M, jira/valid-reference

#2813 Revert "MGMT-19364: Implement UI for external platform"
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/ExternalPlatformsDropdown.tsx
Labels: lgtm, approved, size/M, jira/valid-reference

#2816 MGMT-20056: When user selects CNV operator the MTV operator is also selected
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
Labels: size/XS, jira/valid-reference

#2817 MGMT-20053: If some operators are not supported, we don't select automatically
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/S, jira/valid-reference

#2818 MGMT-20054: Change learn more links dinamically for new operators
  libs/ui-lib/lib/common/config/docs_links.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx
Labels: size/M, jira/valid-reference

#2819 MGMT-20056: When user selects CNV operator the MTV operator is also selected - 2.38
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
Labels: size/XS, jira/valid-reference

#2820 MGMT-20053: If some operators are not supported, we don't select automatically - 2.38
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/S, jira/valid-reference

#2821 MGMT-20054: Change learn more links dinamically for new operators - 2.28
  libs/ui-lib/lib/common/config/docs_links.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx
Labels: size/M, jira/valid-reference
