Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2025-01, with the labels that each got.

#2742 MGMT-19615: Solving problems with history undefined - 2.37
  libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
Labels: lgtm, size/M, jira/valid-reference

#2744 MGMT-19604: Clear alerts when starting cluster installation
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewStep.tsx
Labels: size/XS, jira/valid-reference

#2747 MGMT-19611: If user use bonds+ipv4 withoud bound we need to generate the correct nmstate yaml
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/nmstateYaml.ts
Labels: size/XS, jira/valid-reference

#2748 MGMT-19619: We don't allow users to continue with cluster creation if not agree with cluster limitations
  libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts
Labels: size/S, jira/valid-reference

#2745 MGMT-19587: Show MTU validation only in networking step
  libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts
Labels: size/XS, jira/valid-reference

#2750 MGMT-19160: Remove not highly available cluster text from Control Plane Nodes dropdown
  libs/ui-lib/lib/ocm/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
Labels: size/XS, jira/valid-reference

#2751 MGMT-19587: Show MTU validation only in networking step - 2.37
  libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts
Labels: size/XS, jira/valid-reference

#2752 MGMT-19604: Clear alerts when starting cluster installation - 2.37
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewStep.tsx
Labels: size/XS, jira/valid-reference

#2753 MGMT-19605: Add MTV operator to Installation page - 2.37
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/common/config/constants.ts
Labels: size/XS, jira/valid-reference

#2754 MGMT-19160: Remove not highly available cluster text from Control Plane Nodes dropdown - 2.37
  libs/ui-lib/lib/ocm/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
Labels: size/XS, jira/valid-reference

#2755 MGMT-19611: If user use bonds+ipv4 withoud bound we need to generate the correct nmstate yaml - 2.37
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/data/nmstateYaml.ts
Labels: size/XS, jira/valid-reference

#2756 MGMT-19619: We don't allow users to continue with cluster creation if not agree with cluster limitations - 2.37
  libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts
Labels: size/S, jira/valid-reference

#2760 Solving problems with draft clusters in staging
  libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
Labels: size/XS

#2761 Solving problems with draft clusters in staging - 2.37
  libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
Labels: size/XS

#2762 MGMT-18925: Add tag to know if users are creating hosts from Cisco Intersight
  libs/ui-lib/lib/common/components/clusterConfiguration/DownloadIso.tsx
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageModal.tsx
  libs/ui-lib/lib/ocm/services/ClustersService.ts
Labels: size/M, jira/valid-reference

#2763 MGMT-18925: Add tag to know if users are creating hosts from Cisco Intersight
  libs/ui-lib/lib/common/components/clusterConfiguration/DownloadIso.tsx
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/DiscoveryImageModal.tsx
  libs/ui-lib/lib/ocm/services/ClustersService.ts
Labels: size/M, jira/valid-reference

#2758 MGMT-19592: Do not render menu if there is 0 items
  libs/ui-lib/lib/common/components/hosts/AITableMemo.tsx
Labels: size/XS, jira/valid-reference

#2739 MGMT-19346: Enable 4/5 CPN to Cluster Details Form - 2.14
  libs/locales/lib/en/translation.json
  libs/types/assisted-installer-service.d.ts
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
  libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts
  libs/ui-lib/lib/common/components/clusterWizard/types.ts
Labels: lgtm, size/L, jira/valid-reference

#2759 MGMT-19346: Enable 4/5 CPN to Cluster Details Form
  libs/locales/lib/en/translation.json
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-external-partner-integrations.cy.ts
  libs/ui-lib-tests/cypress/views/forms/ClusterDetails/Fields/ControlPlaneNodesField.ts
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
  libs/ui-lib/lib/common/components/clusterWizard/clusterDetailsValidation.ts
  libs/ui-lib/lib/common/components/clusterWizard/types.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
Labels: lgtm, size/L, jira/valid-reference

#2749 ACM-16229 - Add hosts broken link to document
  libs/ui-lib/lib/cim/components/common/constants.ts
Labels: size/XS

#2746 NO-ISSUE: Fix translation string
  libs/ui-lib/lib/cim/components/InfraEnv/OpenshiftVersionDropdown.tsx
Labels: size/XS, jira/valid-reference

#2766 NO-ISSUE: Fix translation string [2.14-cim]
  libs/ui-lib/lib/cim/components/InfraEnv/OpenshiftVersionDropdown.tsx
Labels: lgtm, size/XS, jira/valid-reference

#2767 ACM-16229: Add hosts broken link to document
  libs/ui-lib/lib/cim/components/common/constants.ts
Labels: size/XS, jira/valid-reference

#2764 MGMT-18987: Allow ISO type configuration from kube API
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/modals/AddHostModal.tsx
  libs/ui-lib/lib/cim/types/k8s/infra-env-k8s-resource.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/DiscoveryImageConfigForm.tsx
  libs/ui-lib/lib/common/components/clusterConfiguration/DiscoveryImageTypeControlGroup.tsx
Labels: lgtm, size/M, jira/valid-reference

#2768 MGMT-19726: Add predefined custom manifests when cluster is created from Assisted Migration
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx
  libs/ui-lib/lib/ocm/config/constants.ts
  libs/ui-lib/lib/ocm/services/ClustersService.ts
Labels: size/L, OCM, jira/valid-reference

#2775 NO-ISSUE: Change actions/upload-artifact@v4 to actions/upload-artifact@v3 in github actions
  .github/workflows/pull-request.yaml
Labels: size/XS, jira/valid-reference

#2774 NO-ISSUE: Link to self managed OpenShift AI
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: lgtm, size/XS, jira/valid-reference
