Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2025-03, with the labels that each got.

#2823 Start with first available cluster
  apps/assisted-disconnected-ui/Containerfile.ocp
  apps/assisted-disconnected-ui/src/components/App.tsx
  apps/assisted-disconnected-ui/src/components/EditWizard.tsx
  apps/assisted-disconnected-ui/src/components/Wizard.tsx
  apps/assisted-disconnected-ui/src/hooks/useCluster.ts
  libs/ui-lib/lib/common/api/index.ts
Labels: lgtm, approved, size/L

#2825 Fix proxy settings, add logging
  apps/assisted-disconnected-ui/proxy/app.go
  apps/assisted-disconnected-ui/proxy/bridge/handler.go
  apps/assisted-disconnected-ui/proxy/log/log.go
  apps/assisted-disconnected-ui/vite.config.ts
Labels: lgtm, approved, size/M

#2824 MGMT-19323: Static IP - changing network IP range after filling host data - UI not showing the error
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/StaticIpForm.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#2828 MGMT-20093: Solving problems with docs links
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: size/XS, jira/valid-reference

#2830 MGMT-20055: Bundle error helper text is unclear
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/XS, jira/valid-reference

#2829 Disconnected UI creates cluster if there is none
  apps/assisted-disconnected-ui/src/components/App.tsx
  apps/assisted-disconnected-ui/src/components/Wizard.tsx
  apps/assisted-disconnected-ui/src/hooks/useCluster.ts
Labels: lgtm, approved, size/M

#2831 AGENT-1131: change pull secret and remove add hosts button in disconnected mode
  apps/assisted-disconnected-ui/src/components/Wizard.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/HostInventory.tsx
Labels: approved, size/S, jira/valid-reference

#2834 MGMT-20096: Virtualization bundle is disabled when selecting LVMS operator
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/M, jira/valid-reference

#2836 MGMT-20096: Virtualization bundle is disabled when selecting LVMS operator - 2.38
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/M, jira/valid-reference

#2838 MGMT-20084: Same behavior on same operators in different selection - for MTV and CNV - 2.38
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-mtv-operator.cy.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
Labels: size/XS, jira/valid-reference

#2839 MGMT-20055: Bundle error helper text is unclear - 2.38
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: size/XS, jira/valid-reference

#2840 MGMT-20093: Solving problems with docs links - 2.38
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: size/XS, jira/valid-reference

#2841 Update owners file
  .github/workflows/push-to-master-disconnected.yaml
  OWNERS
Labels: lgtm, approved, size/M

#2833 Reuse SINGLE_CLUSTER feature
  apps/assisted-disconnected-ui/src/components/App.tsx
  apps/assisted-disconnected-ui/src/components/ClusterPage.tsx
  apps/assisted-disconnected-ui/src/components/CreateClusterWizard.tsx
  apps/assisted-disconnected-ui/src/components/Wizard.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/HostInventory.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardContext.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardContextProvider.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardFooter.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx
  libs/ui-lib/lib/ocm/hooks/index.ts
Labels: approved, size/L

#2845 MGMT-19415: Static IP form - Error test of default GW is incorrect for the case d…
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/commonValidationSchemas.tsx
Labels: approved, size/XS, jira/valid-reference

#2844 MGMT-20086: Change Broadcast to Broadcase in the Bond Type field
  libs/ui-lib/lib/ocm/components/clusterConfiguration/staticIp/components/FormViewHosts/BondsSelect.tsx
Labels: approved, size/XS, jira/valid-reference

#2842 AGENT-1132: Add download kubeconfig wizard page
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizard.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardContextProvider.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/KubeconfigDownload.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/constants.ts
  libs/ui-lib/lib/ocm/components/clusterWizard/wizardTransition.ts
Labels: lgtm, approved, size/M, jira/valid-reference

#2846 Fix yalc cmd
  docs/DEVELOPMENT.md
Labels: lgtm, approved, size/XS

#2848 MGMT-20107: Disable one of the Openshift AI bundles if the other is selected.
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#2854 Update release flow to not force push back to release branch/tag
  .github/workflows/release.yaml
Labels: lgtm, approved, size/S

#2857 MGMT-20135: Implement OpenShift versions select with "all versions" modal
  apps/assisted-disconnected-ui/src/components/CreateClusterWizard.tsx
  docs/DEVELOPMENT.md
  libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-creation.cy.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-custom-ocp-releases.cy.ts
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvFormPage.tsx
  libs/ui-lib/lib/cim/components/InfraEnv/InfraEnvOpenShiftVersionDropdown.tsx
  libs/ui-lib/lib/cim/components/helpers/versions.ts
  libs/ui-lib/lib/common/components/ui/OpenShiftSelectWithSearch.tsx
  libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.css
  libs/ui-lib/lib/common/components/ui/OpenShiftVersionDropdown.tsx
  libs/ui-lib/lib/common/components/ui/OpenShiftVersionModal.css
  libs/ui-lib/lib/common/components/ui/OpenShiftVersionModal.tsx
  libs/ui-lib/lib/common/components/ui/OpenshiftVersionDropdown.css
  libs/ui-lib/lib/common/components/ui/index.ts
  libs/ui-lib/lib/ocm/components/AddHosts/day2Wizard/Day2ClusterDetails.tsx
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabMock.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmClusterDetailsFormFields.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmOpenShiftVersion.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/OcmOpenShiftVersionSelect.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenshiftAIAmdRequirements.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenshiftAINvidiaRequirements.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/review/ReviewPreflightChecks.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerDetailCard.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/AssistedInstallerExtraDetailCard.tsx
  libs/ui-lib/lib/ocm/components/clusterDetail/OpenShiftVersionDetail.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OpenShiftVersionsContext.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/index.ts
  libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx
  libs/ui-lib/lib/ocm/components/clusters/NewClusterPage.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/FeatureSupportLevelProvider.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/ReviewClusterFeatureSupportLevels.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
  libs/ui-lib/lib/ocm/services/OperatorsService.tsx
Labels: lgtm, approved, size/L

#2855 NO-ISSUE: Memoize WizardFooter
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
Labels: lgtm, approved, size/S

#2856 Remove CODEOWNERS, replaced by OWNERS file
  .github/CODEOWNERS
Labels: lgtm, approved

#2861 MGMT-20082: Deploying 4/5 nodes control plane is blocked
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/helpers/versions.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
Labels: approved, size/M, jira/valid-reference

#2865 Set UMN=true in disconnected
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
  libs/ui-lib/lib/ocm/services/ClusterDetailsService.ts
Labels: lgtm, approved, size/S

#2863 MGMT-20082: Deploying 4/5 nodes control plane is blocked
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/helpers/versions.ts
  libs/ui-lib/lib/common/components/clusterConfiguration/ControlPlaneNodesDropdown.tsx
Labels: size/M, jira/valid-reference

#2867 Revert "Set UMN=true in disconnected"
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetailsForm.tsx
  libs/ui-lib/lib/ocm/services/ClusterDetailsService.ts
Labels: lgtm, approved, size/S

#2871 MGMT-19377: [UI] Limit of 63 characters for spoke cluster name should be verified…
  libs/ui-lib/lib/common/components/ui/formik/RichInputField.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#2862 ACM-17500: Fix HostedCluster status CustomKubeconfig name
  libs/ui-lib/lib/cim/components/Hypershift/DetailsPage/HypershiftKubeconfigDownload.tsx
  libs/ui-lib/lib/cim/components/Hypershift/types.ts
Labels: lgtm, approved, ok-to-test, size/XS, jira/valid-reference

#2866 AGENT-1143: add reset button to disconnected assisted installer ui
  apps/assisted-disconnected-ui/src/components/ClusterPage.tsx
  apps/assisted-disconnected-ui/src/components/CreateClusterWizard.tsx
  apps/assisted-disconnected-ui/src/components/ResetSingleClusterModal.tsx
  libs/locales/.i18next-parser.config.cjs
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/common/components/ui/WizardFooter.tsx
  libs/ui-lib/lib/common/hooks/index.ts
  libs/ui-lib/lib/common/index.ts
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardFooter.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx
  libs/ui-lib/lib/ocm/components/hosts/ModalDialogsContext.tsx
Labels: lgtm, approved, size/L, jira/valid-reference

#2868 MGMT-19753: Mismatch in available options in CPU Architecture dropdown menu on Standalone cluster details page and Infraenv create Page
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/common/CpuArchitectureDropdown.tsx
Labels: lgtm, approved, size/M, jira/valid-reference

#2876 MGMT-19753: Mismatch in available options in CPU Architecture dropdown menu on Standalone cluster details page and Infraenv create Page
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDeploymentDetailsForm.tsx
  libs/ui-lib/lib/cim/components/ClusterDeployment/ClusterDetailsFormFields.tsx
  libs/ui-lib/lib/cim/components/common/CpuArchitectureDropdown.tsx
Labels: size/M, jira/valid-reference

#2878 NO-ISSUE: Remove console log
  libs/ui-lib/lib/common/components/storage/DisksTable.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#2875 MGMT-19287: fix grid in host discovery alignment
  libs/ui-lib/lib/common/components/hosts/HostPropertyValidationPopover.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#2877 MGMT-20116: fix bug: UMN documentation link returns 404
  libs/ui-lib/lib/common/config/docs_links.ts
Labels: lgtm, approved, size/S, jira/valid-reference

#2880 MGMT-20182: Day2 - host not shown in the UI session that generated it, but is shown in another session
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
Labels: lgtm, approved, size/S, jira/valid-reference
