Repository openshift-assisted/assisted-installer-ui, pull requests merged in 2025-04, with the labels that each got.

#2882 MGMT-20217: Assisted Operators Review
  libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-updates.cy.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-mce-operator.cy.ts
  libs/ui-lib-tests/cypress/integration/use-cases/create-cluster/with-mtv-operator.cy.ts
  libs/ui-lib-tests/cypress/views/forms/Operators/OperatorsForm.ts
  libs/ui-lib-tests/cypress/views/operatorsPage.ts
  libs/ui-lib/lib/common/config/docs_links.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AmdGpuCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/AuthorinoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/KmmCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LsoCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/LvmCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MceCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/MtvOperatorCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NmstateCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeFeatureDiscoveryCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NvidiaGpuCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OdfCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OpenShiftAICheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OscCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/PipelinesChekbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServerlessCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/ServicemeshCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/VirtualizationRequirements.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: lgtm, approved, size/L, jira/valid-reference

#2884 MGMT-20200: Add new operators to virtualization bundle
  libs/locales/lib/en/translation.json
  libs/types/assisted-installer-service.d.ts
  libs/ui-lib/lib/common/config/constants.ts
  libs/ui-lib/lib/common/config/docs_links.ts
  libs/ui-lib/lib/common/types/clusters.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/FenceAgentsRemediationCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/KubeDeschedulerCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeHealthcheckCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/NodeMaintenanceOperatorCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/SelfNodeRemediationCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/SupportedOperators.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/VirtualizationRequirements.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/Operators.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
  libs/ui-lib/lib/ocm/services/OperatorsService.tsx
Labels: lgtm, approved, size/L, jira/valid-reference

#2886 MGMT-20253: Virtualization operator doesn't require MTV
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#2893 MGMT-20291: Add data-testid to Single Operators section in Operators page
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#2895 MGMT-20182: Day2 - host not shown in the UI session that generated it, but is shown in another session - 2.38
  libs/ui-lib/lib/ocm/components/HostsClusterDetailTab/HostsClusterDetailTabContent.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#2894 AGENT-1160: ABI - add finalizing page
  apps/assisted-disconnected-ui/src/components/ClusterPage.tsx
  apps/assisted-disconnected-ui/src/components/SingleClusterFinalizerPage.tsx
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/common/components/clusterDetail/index.ts
  libs/ui-lib/lib/ocm/components/clusterDetail/RebootNodeZeroModal.css
  libs/ui-lib/lib/ocm/components/clusterDetail/RebootNodeZeroModal.tsx
  libs/ui-lib/lib/ocm/components/clusters/ClusterPage.tsx
Labels: lgtm, approved, size/L, jira/valid-reference

#2904 AGENT-1180: ABI: Set TechPreviewNoUpgrade on the target cluster
  libs/ui-lib/lib/common/api/assisted-service/ClustersAPI.ts
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx
Labels: lgtm, approved, size/M, jira/valid-reference

#2906 MGMT-20351: selecting CNV - not able to deselect it using UI
  libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-updates.cy.ts
  libs/ui-lib-tests/cypress/views/operatorsPage.ts
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
Labels: lgtm, approved, size/XS, jira/valid-reference

#2907 MGMT-20352: selecting Openshift AI - LVMS should be blocked
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
Labels: lgtm, approved, size/S, jira/valid-reference

#2908 MGMT-20354: LSO Operator Visually Unchecked in UI After Toggling Virt Bundle Whil…
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#2909 MGMT-20351: selecting CNV - not able to deselect it using UI - new changes
  libs/ui-lib-tests/cypress/integration/ui-behaviour/cluster-updates.cy.ts
  libs/ui-lib-tests/cypress/views/operatorsPage.ts
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/CnvCheckbox.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsStep.tsx
  libs/ui-lib/lib/ocm/components/featureSupportLevels/featureStateUtils.ts
Labels: lgtm, approved, size/S, jira/valid-reference

#2911 move Set TechPreviewNoUpgrade on the target cluster
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterDetails.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/HostDiscovery.tsx
Labels: lgtm, approved, size/M

#2913 MGMT-20330: fix hosts table showing BMC hosts from hub cluster
  libs/ui-lib/lib/cim/components/helpers/toAssisted.ts
Labels: lgtm, approved, size/XS, jira/valid-reference

#2918 move Set TechPreviewNoUpgrade on the target cluster to networking step
  libs/ui-lib/lib/ocm/components/clusterConfiguration/networkConfiguration/NetworkConfigurationForm.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/HostDiscovery.tsx
Labels: lgtm, approved, size/M

#2919 NO-ISSUE: Add LVM operator for ABI flow
  libs/ui-lib/lib/common/config/constants.ts
Labels: lgtm, approved, size/XS, jira/valid-reference

#2922 NO-ISSUE: Move ocm styles to ocm lib
  libs/ui-lib/lib/common/index.ts
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.css
  libs/ui-lib/lib/ocm/components/clusterDetail/ClusterDetailsButtonGroup.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#2903 MGMT-19552: change deprecated wizard component
  libs/ui-lib/lib/common/components/clusterWizard/ClusterWizardStep.tsx
  libs/ui-lib/lib/common/components/ui/WizardNavItem.tsx
  libs/ui-lib/lib/ocm/components/AddHosts/day2Wizard/Day2Wizard.tsx
  libs/ui-lib/lib/ocm/components/AddHosts/day2Wizard/Day2WizardNav.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/ClusterWizardNavigation.tsx
Labels: lgtm, approved, size/M, jira/valid-reference

#2923 MGMT-20288: Show all available versions is ignoring basic version format
  libs/ui-lib/lib/cim/components/helpers/versions.ts
Labels: lgtm, approved, size/XS, jira/valid-reference

#2921 NO-ISSUE: Export common/utils from CIM
  libs/ui-lib/lib/cim/index.ts
Labels: lgtm, approved, size/XS, jira/valid-reference

#2900 MGMT-19551: change deprecated select component
  libs/locales/lib/en/translation.json
  libs/ui-lib/lib/cim/components/InfraEnv/InfraTableToolbar.tsx
  libs/ui-lib/lib/common/components/ui/ClusterEventsToolbar.tsx
  libs/ui-lib/lib/common/components/ui/formik/MultiSelectField.tsx
  libs/ui-lib/lib/common/components/ui/formik/types.ts
  libs/ui-lib/lib/common/components/ui/utils.ts
  libs/ui-lib/lib/ocm/components/clusters/ClustersListToolbar.tsx
Labels: lgtm, approved, size/L, jira/valid-reference

#2927 Bundle badge is based on operators support level
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsBundle.tsx
Labels: lgtm, approved, size/M

#2929 MGMT-20412: Adding data-testid to operators checkbox
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/OperatorCheckbox.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference

#2931 Fix badge for bundles with no feature ID
  libs/ui-lib/lib/common/components/newFeatureSupportLevels/NewFeatureSupportLevelBadge.tsx
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/bundleSpecs.tsx
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsBundle.tsx
Labels: lgtm, approved, size/M

#2933 Do not allow virtualization bundle on SNO clusters
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/bundleSpecs.tsx
Labels: lgtm, approved, size/XS

#2935 Fix bundle cards popover in firefox
  libs/ui-lib/lib/ocm/components/clusterWizard/OperatorsBundle.tsx
Labels: lgtm, approved, size/XS

#2934 add console url to credentials download file
  libs/ui-lib/lib/ocm/components/clusterWizard/CredentialsDownload.tsx
Labels: lgtm, approved, size/M

#2937 Update msg in ABI finalizer page.
  apps/assisted-disconnected-ui/src/components/SingleClusterFinalizerPage.tsx
  libs/locales/lib/en/translation.json
Labels: lgtm, approved, size/XS

#2940 NO-ISSUE: Add owners file to releases/2.14-cim
  OWNERS
Labels: lgtm, size/S, do-not-merge/invalid-owners-file, jira/valid-reference

#2943 MGMT-20237: Change tooltip for Openshift AI bundle
  libs/ui-lib/lib/ocm/components/clusterConfiguration/operators/bundleSpecs.tsx
Labels: lgtm, approved, size/S, jira/valid-reference

#2944 MGMT-20520: Change learn more link for Kube Descheduler operator
  libs/ui-lib/lib/common/components/operators/operatorSpecs.tsx
Labels: lgtm, approved, size/XS, jira/valid-reference
